from __future__ import annotations

import importlib
import importlib.util
import json
from copy import deepcopy
from datetime import UTC, datetime
from uuid import UUID

import pytest

from app.ai.client import LLMClient, LLMProviderError
from app.underwriting.hashing import canonical_hash

PROJECT_ID = UUID("6601431f-d188-48c0-bb10-bd5e78eafc28")
PREPARATION_ID = UUID("7133b4f4-abcd-4e8a-89e7-6b8218c681c8")
CUTOFF = datetime(2026, 8, 25, 23, 59, 59, tzinfo=UTC)
QUOTE = "Cloud customers expanded their use of infrastructure and platform services."
RISK_QUOTE = (
    "Infrastructure investment may precede the revenue generated by customer demand."
)


def _module():
    assert importlib.util.find_spec("app.ai.company_research") is not None, (
        "company research needs a source-grounded LLM generator"
    )
    return importlib.import_module("app.ai.company_research")


def _evidence():
    return {
        "fixture_content_hash": "b" * 64,
        "cutoff": CUTOFF.isoformat(),
        "company_external_key": "NASDAQ:GOOGL:COMPANY",
        "security_external_keys": ["NASDAQ:GOOG", "NASDAQ:GOOGL"],
        "facts": [
            {
                "fact_key": "cloud_revenue",
                "company_external_key": "NASDAQ:GOOGL:COMPANY",
                "business_module": "cloud",
                "metric_key": "revenue",
                "value": "58700",
                "value_kind": "reported",
                "currency": "USD",
                "unit": "USD_million",
                "period_start": "2025-01-01",
                "period_end": "2025-12-31",
                "published_at": "2026-02-04T12:00:00+00:00",
                "available_at": "2026-02-04T12:00:00+00:00",
                "source_role": "company_disclosure",
                "source_url": "https://issuer.test/annual.pdf",
                "source_locator": "Cloud results",
                "raw_hash": "a" * 64,
            }
        ],
    }


def _bundle(evidence):
    excerpts = [
        {
            "excerpt_id": "annual-cloud",
            "source_id": "annual",
            "raw_hash": "a" * 64,
            "source_url": "https://issuer.test/annual.pdf",
            "locator": "Cloud results",
            "text": f"{QUOTE}\n{RISK_QUOTE}",
        }
    ]
    value = {
        "schema_version": "company-research.live-source-bundle.v1",
        "source_mode": "live_http_verified",
        "company_external_key": evidence["company_external_key"],
        "cutoff_at": CUTOFF.isoformat(),
        "governed_manifest_hash": "b" * 64,
        "evidence_payload_hash": canonical_hash(evidence),
        "captured_at": "2026-09-09T12:00:00+00:00",
        "documents": [
            {
                "source_id": "annual",
                "source_url": "https://issuer.test/annual.pdf",
                "raw_hash": "a" * 64,
                "fact_keys": ["cloud_revenue"],
            }
        ],
        "excerpts": excerpts,
        "excerpts_hash": canonical_hash(excerpts),
    }
    value["bundle_hash"] = canonical_hash(value)
    return value


def _input():
    evidence = _evidence()
    return {
        "project_id": PROJECT_ID,
        "preparation_id": PREPARATION_ID,
        "request_hash": "c" * 64,
        "strategy_version": "alphabet.v1",
        "user_focus": "云业务需求兑现与基础设施资本开支之间的关系",
        "cutoff_at": CUTOFF,
        "company_name": "Alphabet",
        "source_bundle": _bundle(evidence),
        "evidence_payload": evidence,
    }


def _finding(title="需求与现金投入的时间差", *, counter=False):
    return {
        "title": title,
        "text": "客户使用基础设施服务的增加可以支撑收入，但资本投入先于收入兑现，因此需要结合客户需求持续性判断现金回报。",
        "citations": [
            {"excerpt_id": "annual-cloud", "quote": RISK_QUOTE if counter else QUOTE}
        ],
        "fact_keys": ["cloud_revenue"],
    }


def _response():
    return {
        "business_analysis": [_finding("收入如何形成"), _finding("成本与资本需求")],
        "operating_drivers": [_finding("客户需求持续性"), _finding("资本投入节奏")],
        "candidate_assumptions": [
            _finding("需求延续的候选假设"),
            _finding("资本开支回报的候选假设"),
        ],
        "counterevidence": [_finding("需求兑现可能晚于投入", counter=True)],
        "verification_questions": [_finding("观察需求向现金回报的传导")],
        "report_sections": [
            _finding("商业模式"),
            _finding("经营判断"),
            _finding("研究边界", counter=True),
        ],
    }


class ExplicitTestClient:
    model_version = "explicit-test-client"

    def __init__(self, response=None):
        self.response = _response() if response is None else response
        self.calls = []

    def chat_json(self, messages, schema_hint=""):
        self.calls.append((deepcopy(messages), schema_hint))
        if isinstance(self.response, Exception):
            raise self.response
        return deepcopy(self.response)


def _generate(*, response=None, inputs=None):
    module = _module()
    client = ExplicitTestClient(response)
    result = module.CompanyResearchDraftGenerator(client).generate(
        **(inputs or _input())
    )
    return module, client, result


def _rehash_bundle(bundle):
    bundle["excerpts_hash"] = canonical_hash(bundle["excerpts"])
    bundle["bundle_hash"] = canonical_hash(
        {key: value for key, value in bundle.items() if key != "bundle_hash"}
    )


def test_grounded_draft_contains_real_excerpt_focus_and_resolved_citations():
    module, client, generated = _generate()
    messages, hint = client.calls[0]
    prompt = json.loads(messages[1]["content"])
    assert hint == "company_research_draft"
    assert prompt["user_focus"] == _input()["user_focus"]
    assert (
        prompt["excerpts"][0]["text"]
        == _input()["source_bundle"]["excerpts"][0]["text"]
    )
    assert prompt["facts"][0]["value"] == "58700"
    assert generated.prompt_version == module.PROMPT_VERSION
    assert generated.model_version == client.model_version
    assert generated.payload["candidate_status"] == "machine_draft"
    citation = generated.payload["business_analysis"][0]["citations"][0]
    assert citation == {
        "excerpt_id": "annual-cloud",
        "quote": QUOTE,
        "source_id": "annual",
        "raw_hash": "a" * 64,
        "source_url": "https://issuer.test/annual.pdf",
        "locator": "Cloud results",
    }
    assert (
        generated.payload["source_bundle_hash"]
        == _input()["source_bundle"]["bundle_hash"]
    )
    assert generated.output_hash == canonical_hash(
        {"payload": generated.payload, "markdown": generated.markdown}
    )
    assert "客户使用基础设施服务" in generated.markdown
    assert "58700 USD\\_million" in generated.markdown
    assert "2026-08-25" in generated.markdown
    assert "未经人工确认" in generated.markdown
    assert "候选假设" in generated.markdown
    assert "反证" in generated.markdown
    assert "[来源" in generated.markdown
    assert "https://issuer.test/annual.pdf" in generated.markdown
    assert "正式估值" in generated.markdown


def test_focus_is_bound_into_prompt_and_input_hash_not_only_report_heading():
    first = _input()
    second = deepcopy(first)
    second["user_focus"] = "搜索广告竞争与流量获取成本"
    _, client_a, a = _generate(inputs=first)
    _, client_b, b = _generate(inputs=second)
    assert client_a.calls[0][0][1]["content"] != client_b.calls[0][0][1]["content"]
    assert a.input_hash != b.input_hash
    assert a.output_hash != b.output_hash


def test_generation_is_replayable_and_does_not_mutate_frozen_inputs():
    inputs = _input()
    original = deepcopy(inputs)
    _, _, first = _generate(inputs=inputs)
    _, _, second = _generate(inputs=inputs)
    assert first == second
    assert inputs == original


@pytest.mark.parametrize(
    "mutation",
    [
        lambda value: value.update(reviewed=True),
        lambda value: value.update(valuation_set={"fair_value": 100}),
        lambda value: value["business_analysis"][0].update(reviewer="human:local-user"),
        lambda value: value["candidate_assumptions"][0].update(value="0.15"),
        lambda value: value["report_sections"][0].update(markdown="made up"),
        lambda value: value["counterevidence"].clear(),
        lambda value: value["business_analysis"][0].update(text=" "),
        lambda value: value["report_sections"][0].update(
            text="预期收入将增长 80%，合理价值为 999 美元。"
        ),
        lambda value: value["candidate_assumptions"][0].update(
            text="我们假设增长百分之三十，因而直接提高现金流预测并得出投资结论。"
        ),
        lambda value: value["business_analysis"][0]["citations"].clear(),
        lambda value: value["business_analysis"][0]["citations"][0].update(
            excerpt_id="foreign"
        ),
        lambda value: value["business_analysis"][0]["citations"][0].update(
            quote="This is a plausible but invented quotation."
        ),
        lambda value: value["business_analysis"][0]["citations"][0].update(
            raw_hash="f" * 64
        ),
        lambda value: value["business_analysis"][0].update(
            fact_keys=["made_up_revenue"]
        ),
        lambda value: value["business_analysis"][0].update(
            fact_keys=["cloud_revenue", "cloud_revenue"]
        ),
    ],
)
def test_rejects_unfounded_or_authority_forging_provider_output(mutation):
    module = _module()
    response = _response()
    mutation(response)
    with pytest.raises(module.CompanyResearchDraftProviderError) as caught:
        _generate(response=response)
    assert str(caught.value) == module.DRAFT_PROVIDER_ERROR


@pytest.mark.parametrize("response", [[], "secret-invalid-body", 42, None])
def test_non_object_provider_response_is_a_safe_error(response):
    module = _module()
    client = ExplicitTestClient()
    client.response = response
    with pytest.raises(module.CompanyResearchDraftProviderError) as caught:
        module.CompanyResearchDraftGenerator(client).generate(**_input())
    assert str(caught.value) == module.DRAFT_PROVIDER_ERROR
    assert caught.value.__cause__ is None


@pytest.mark.parametrize(
    "mutation",
    [
        lambda value: value["source_bundle"].update(bundle_hash="f" * 64),
        lambda value: value["source_bundle"].update(source_mode="fixture"),
        lambda value: value["source_bundle"].update(excerpts=[]),
        lambda value: value["source_bundle"]["excerpts"][0].update(text=" "),
        lambda value: value["source_bundle"]["excerpts"][0].update(text="x" * 8501),
        lambda value: value["source_bundle"]["excerpts"][0].update(raw_hash="f" * 64),
        lambda value: value["source_bundle"]["excerpts"][0].update(
            source_url="javascript:alert(1)"
        ),
        lambda value: value["source_bundle"]["excerpts"].append(
            deepcopy(value["source_bundle"]["excerpts"][0])
        ),
        lambda value: value["evidence_payload"]["facts"][0].update(value="999999"),
        lambda value: value.update(user_focus="x" * 2001),
        lambda value: value.update(cutoff_at=CUTOFF.replace(tzinfo=None)),
    ],
)
def test_invalid_frozen_input_is_rejected_before_any_provider_call(mutation):
    module = _module()
    inputs = _input()
    mutation(inputs)
    client = ExplicitTestClient()
    with pytest.raises(module.CompanyResearchDraftInputError) as caught:
        module.CompanyResearchDraftGenerator(client).generate(**inputs)
    assert str(caught.value) == module.DRAFT_INPUT_ERROR
    assert client.calls == []


def test_rehashed_excerpt_cannot_substitute_an_unregistered_source():
    module = _module()
    inputs = _input()
    inputs["source_bundle"]["excerpts"][0]["source_id"] = "foreign"
    _rehash_bundle(inputs["source_bundle"])
    with pytest.raises(module.CompanyResearchDraftInputError):
        _generate(inputs=inputs)


def test_rehashed_excerpt_cannot_substitute_a_registered_document_hash():
    module = _module()
    inputs = _input()
    inputs["source_bundle"]["excerpts"][0]["raw_hash"] = "f" * 64
    _rehash_bundle(inputs["source_bundle"])
    with pytest.raises(module.CompanyResearchDraftInputError):
        _generate(inputs=inputs)


@pytest.mark.parametrize(
    "error", [LLMProviderError("secret token=api-key"), TimeoutError("secret URL")]
)
def test_provider_failure_is_safe_without_fallback_research(error):
    module = _module()
    with pytest.raises(module.CompanyResearchDraftProviderError) as caught:
        _generate(response=error)
    assert str(caught.value) == module.DRAFT_PROVIDER_ERROR
    assert caught.value.__cause__ is None


def test_builtin_llm_mock_is_forbidden_even_in_test_environment():
    module = _module()
    with pytest.raises(module.CompanyResearchDraftInputError):
        module.CompanyResearchDraftGenerator(
            LLMClient(model_version="mock-live", mock=True)
        )


def test_duck_typed_test_client_is_forbidden_outside_explicit_test_environment(
    monkeypatch,
):
    module = _module()
    monkeypatch.setenv("APP_ENV", "production")
    with pytest.raises(module.CompanyResearchDraftInputError):
        module.CompanyResearchDraftGenerator(ExplicitTestClient())


def test_numeric_values_are_allowed_in_exact_source_quotes():
    inputs = _input()
    exact_quote = "Reported Cloud revenue was 58700 million dollars."
    inputs["source_bundle"]["excerpts"][0]["text"] += "\n" + exact_quote
    _rehash_bundle(inputs["source_bundle"])
    response = _response()
    response["business_analysis"][0]["citations"][0]["quote"] = exact_quote
    _, _, generated = _generate(response=response, inputs=inputs)
    assert (
        generated.payload["business_analysis"][0]["citations"][0]["quote"]
        == exact_quote
    )


def test_frozen_excerpt_boundary_whitespace_is_preserved_in_the_prompt():
    inputs = _input()
    text = "\n " + inputs["source_bundle"]["excerpts"][0]["text"] + " \n"
    inputs["source_bundle"]["excerpts"][0]["text"] = text
    _rehash_bundle(inputs["source_bundle"])
    _, client, generated = _generate(inputs=inputs)
    prompt = json.loads(client.calls[0][0][1]["content"])
    assert prompt["excerpts"][0]["text"] == text
    assert (
        generated.payload["source_bundle_hash"]
        == inputs["source_bundle"]["bundle_hash"]
    )


def test_saved_generation_can_revalidate_without_another_provider_call():
    module, client, generated = _generate()
    assert hasattr(module, "validate_saved_generation"), (
        "persisted drafts need pure replay validation"
    )
    inputs = _input()
    actual = module.validate_saved_generation(
        generated.payload,
        generated.markdown,
        source_bundle=inputs["source_bundle"],
        evidence_payload=inputs["evidence_payload"],
        model_version=generated.model_version,
    )
    assert actual == generated.output_hash
    assert len(client.calls) == 1


@pytest.mark.parametrize(
    "mutation",
    [
        lambda payload, markdown: (
            payload | {"reviewer": "human:local-user"},
            markdown,
        ),
        lambda payload, markdown: (
            payload | {"candidate_status": "human_confirmed"},
            markdown,
        ),
        lambda payload, markdown: (
            payload | {"source_bundle_hash": "f" * 64},
            markdown,
        ),
        lambda payload, markdown: (
            payload | {"evidence_payload_hash": "f" * 64},
            markdown,
        ),
        lambda payload, markdown: (payload | {"user_focus": "另一个重点"}, markdown),
        lambda payload, markdown: (
            payload | {"cutoff_at": "2026-09-09T00:00:00+00:00"},
            markdown,
        ),
        lambda payload, markdown: (payload, markdown + "\nAlready human approved.\n"),
        lambda payload, markdown: (
            payload,
            markdown.replace("explicit\\-test\\-client", "another-model"),
        ),
    ],
)
def test_saved_generation_rejects_changed_content_and_serialization(mutation):
    module, _, generated = _generate()
    assert hasattr(module, "validate_saved_generation"), (
        "persisted drafts need pure replay validation"
    )
    payload, markdown = mutation(deepcopy(generated.payload), generated.markdown)
    inputs = _input()
    with pytest.raises(module.CompanyResearchDraftInputError) as caught:
        module.validate_saved_generation(
            payload,
            markdown,
            source_bundle=inputs["source_bundle"],
            evidence_payload=inputs["evidence_payload"],
            model_version=generated.model_version,
        )
    assert str(caught.value) == module.DRAFT_INPUT_ERROR


@pytest.mark.parametrize(
    "field,value",
    [
        ("source_id", "foreign-source"),
        ("raw_hash", "f" * 64),
        ("source_url", "https://foreign.test/disclosure"),
        ("locator", "made up locator"),
        ("quote", "A quotation that does not exist in the original document."),
    ],
)
def test_saved_generation_rejects_tampered_resolved_citation(field, value):
    module, _, generated = _generate()
    assert hasattr(module, "validate_saved_generation"), (
        "persisted drafts need pure replay validation"
    )
    payload = deepcopy(generated.payload)
    payload["business_analysis"][0]["citations"][0][field] = value
    inputs = _input()
    with pytest.raises(module.CompanyResearchDraftInputError):
        module.validate_saved_generation(
            payload,
            generated.markdown,
            source_bundle=inputs["source_bundle"],
            evidence_payload=inputs["evidence_payload"],
            model_version=generated.model_version,
        )


def test_input_receipt_hash_matches_generation_without_calling_the_provider():
    module = _module()
    generator = module.CompanyResearchDraftGenerator(ExplicitTestClient())
    assert hasattr(generator, "input_hash_for"), (
        "failed calls need a pure input receipt"
    )
    client = generator._client
    expected = generator.input_hash_for(**_input())
    assert client.calls == []
    generated = generator.generate(**_input())
    assert expected == generated.input_hash
    assert len(client.calls) == 1


def test_failed_provider_call_retains_a_reconstructible_input_receipt():
    module = _module()
    client = ExplicitTestClient(LLMProviderError("secret body"))
    generator = module.CompanyResearchDraftGenerator(client)
    assert hasattr(generator, "input_hash_for"), (
        "failed calls need a pure input receipt"
    )
    expected = generator.input_hash_for(**_input())
    with pytest.raises(module.CompanyResearchDraftProviderError):
        generator.generate(**_input())
    assert generator.input_hash_for(**_input()) == expected
    assert len(client.calls) == 1


def test_input_receipts_for_interleaved_requests_do_not_share_mutable_state():
    module = _module()
    client = ExplicitTestClient()
    generator = module.CompanyResearchDraftGenerator(client)
    assert hasattr(generator, "input_hash_for"), (
        "failed calls need a pure input receipt"
    )
    first = _input()
    second = deepcopy(first)
    second["user_focus"] = "广告业务的竞争壁垒"
    original = deepcopy(first)
    a = generator.input_hash_for(**first)
    b = generator.input_hash_for(**second)
    assert a != b
    assert generator.generate(**first).input_hash == a
    assert generator.input_hash_for(**second) == b
    assert first == original
    assert len(client.calls) == 1


def test_input_receipt_rejects_invalid_frozen_inputs_without_provider_use():
    module = _module()
    client = ExplicitTestClient()
    generator = module.CompanyResearchDraftGenerator(client)
    assert hasattr(generator, "input_hash_for"), (
        "failed calls need a pure input receipt"
    )
    inputs = _input()
    inputs["source_bundle"]["bundle_hash"] = "f" * 64
    with pytest.raises(module.CompanyResearchDraftInputError):
        generator.input_hash_for(**inputs)
    assert client.calls == []
