(function () {
  "use strict";

  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    for (const child of Object.values(value)) deepFreeze(child);
    return Object.freeze(value);
  }

  window.PROTOTYPE_DATA = deepFreeze({
    case: {
      id: "RC-AIC-2025-01",
      title: "AI 算力需求能否穿透至可验证的收入与持仓表达",
      question: "截至 2025-06-30，AI 算力资本开支能否通过已披露订单、交付与收入，形成可审计且仍需持续验证的产业链判断？",
      researchObject: "从云厂商资本开支，经芯片、互连与系统交付，到分部收入的 AI 算力产业链",
      phenomenon: "AI 资本开支持续扩张，但订单、交付与收入确认的节奏出现分化",
      researchPeriod: { start: "2025-01-01", end: "2027-12-31" },
      researchPlan: {
        revision: "RP-AIC-2025-01-v1",
        reusableAssets: {
          documentIds: ["DOC-MSFT-FY25Q3", "DOC-NVDA-FY26Q1", "DOC-MSFT-FY25Q3-CALL", "DOC-TSMC-2025M05"],
          statementIds: ["ST-001", "ST-002", "ST-004"],
          metricIds: ["M-NVDA-DC-REV", "M-TSMC-M05-YOY"],
          evidenceLinkIds: ["EL-001", "EL-002", "EL-004"],
          relatedCaseIds: ["RC-AIC-2025-01"],
        },
        candidateReuseAssetIds: ["DOC-BRCM-FY25Q2", "ST-003"],
        plannedProviderQueries: [
          {
            id: "PQ-JY-INDUSTRY",
            provider: "juyuan",
            capability: "industry_analysis_view",
            mode: "capability_probe",
            status: "planned",
            exposureStatus: "probe_required",
            purpose: "查找产业链供需与交付约束的可核验出处，不直接采用观点结论",
            dateScope: { start: "2025-01-01", end: "2025-06-30" },
            cutoff: "2025-06-30",
            intendedArtifact: "带来源版本与原文区段的行业材料候选件",
          },
          {
            id: "PQ-JY-FILING",
            provider: "juyuan",
            capability: "announcement_filing_fulltext",
            mode: "capability_probe",
            status: "planned",
            exposureStatus: "probe_required",
            purpose: "核对订单、交付与分部收入是否在同一主体披露中对齐",
            dateScope: { start: "2025-01-01", end: "2025-06-30" },
            cutoff: "2025-06-30",
            intendedArtifact: "截止日前公告财报原文的冻结文档版本",
          },
          {
            id: "PQ-JY-HOLDING",
            provider: "juyuan",
            capability: "fund_holding_detail",
            mode: "capability_probe",
            status: "planned",
            exposureStatus: "probe_required",
            purpose: "补齐披露期持仓映射，仅用于表达层核对",
            dateScope: { start: "2025-03-31", end: "2025-06-30" },
            cutoff: "2025-06-30",
            intendedArtifact: "带报告期、份额类别与来源版本的持仓披露件",
          },
        ],
        collectionTasks: [
          {
            id: "CT-REUSE-FROZEN",
            label: "复用当前快照中的已冻结资料与数据",
            state: "reused_frozen",
            cutoff: "2025-06-30",
            assetIds: ["DOC-MSFT-FY25Q3", "DOC-NVDA-FY26Q1", "DOC-MSFT-FY25Q3-CALL", "DOC-TSMC-2025M05", "ST-001", "ST-002", "ST-004", "M-NVDA-DC-REV", "M-TSMC-M05-YOY", "EL-001", "EL-002", "EL-004"],
          },
          {
            id: "CT-PROBE-JY",
            label: "确认计划能力是否实际暴露并已获授权",
            state: "awaiting_capability_probe",
            cutoff: "2025-06-30",
            providerQueryIds: ["PQ-JY-INDUSTRY", "PQ-JY-FILING", "PQ-JY-HOLDING"],
          },
          {
            id: "CT-HOLDING-PERMISSION",
            label: "历史持仓读取受当前凭证权限阻塞",
            state: "blocked_permission",
            cutoff: "2025-06-30",
            providerQueryId: "PQ-JY-HOLDING",
          },
        ],
        positiveEvidenceSearches: [
          { id: "PS-001", label: "云厂商 AI 资本开支、订单积压与分部收入同向披露", scope: "2025-01-01 至 2025-06-30 · 云厂商正式披露", status: "planned" },
        ],
        negativeEvidenceSearches: [
          { id: "NS-001", label: "资本开支下调、交付延迟、订单取消或收入口径不匹配", scope: "2025-01-01 至 2025-06-30 · 发行人披露与反面线索", status: "planned" },
        ],
        resultMetricIds: ["M-NVDA-DC-REV", "M-TSMC-M05-YOY"],
        currentGapFactorIds: ["F-C-01", "F-X-01"],
      },
      dataCenter: {
        selectedMetricId: "M-NVDA-DC-REV",
        catalog: [
          { id: "M-NVDA-DC-REV", label: "NVIDIA 数据中心业务收入", entity: "NVIDIA", cadence: "季度", state: "部分观测可用于截止日" },
          { id: "M-TSMC-M05-YOY", label: "台积电月度营收同比增幅", entity: "TSMC", cadence: "月度", state: "截止日可用" },
          { id: "M-FUND-HOLDING-HIST", label: "基金历史持仓权重", entity: "示例基金范围", cadence: "报告期", state: "权限缺口 · 暂无冻结值" },
        ],
        selectedMetric: {
          name: "NVIDIA 数据中心业务收入",
          entity: "NVIDIA",
          value: "391",
          unit: "亿美元",
          period: "2026 财年第一季度",
          asOf: "2025-04-27",
          publishedAt: "2025-05-28 20:05 UTC",
          availableAt: "2025-05-28 20:13 UTC",
          acquiredAt: "2025-06-30 18:10 CST",
          source: "NVIDIA Form 10-Q · sec-10q-2025-05-28-v1",
          methodology: "公司披露的 Data Center 分部收入；不以资本开支、订单或模型推算替代。",
          revision: "2025-07-02 来源确认修订",
          providerRunId: "PR-001",
          failureMeaning: "刷新失败只表示本次未取得新版本，不撤销或推测替换已冻结观测。",
        },
        series: [
          { period: "FY25 Q2", value: "263", numericValue: 263, acquiredAt: "2024-08-28", cutoffUsable: true, status: "截止日可用" },
          { period: "FY25 Q3", value: "308", numericValue: 308, acquiredAt: "2024-11-20", cutoffUsable: true, status: "截止日可用" },
          { period: "FY25 Q4", value: "356", numericValue: 356, acquiredAt: "2025-02-26", cutoffUsable: true, status: "截止日可用" },
          { period: "FY26 Q1", value: "391", numericValue: 391, acquiredAt: "2025-06-30", cutoffUsable: true, status: "截止日可用" },
          { period: "来源确认", value: "391", numericValue: 391, acquiredAt: "2025-07-02", cutoffUsable: false, status: "案例截止日不可用 · 现在已可用" },
        ],
        revisionComparison: {
          oldValue: "391 亿美元",
          oldSource: "发行人业绩材料 · 2025-05-28 已公开",
          oldCutoffMeaning: "可用于 RS-2025-06-30-v3",
          newValue: "391 亿美元",
          newSource: "Form 10-Q 来源确认 · 2025-07-02 才采集",
          newCutoffMeaning: "案例截止日不可用 · 现在已可用",
          whyItMatters: "数值未变，但来源从初始披露升级为监管文件。新来源只能进入后续快照，不能回写 2025-06-30 当时可知的信息。",
        },
        plannedAttempt: {
          id: "PQ-JY-FILING",
          label: "公告财报原文能力探测",
          state: "计划中 · 尚未执行",
          meaning: "这是下一次能力探测，不是历史成功，也不是正在运行的任务。",
        },
      },
      cutoff: "2025-06-30",
      snapshotId: "RS-2025-06-30-v3",
      state: "awaiting_validation",
      aiLabel: "AI 草案 · 未经人工复核",
      provisionalAssessment: "已复核材料支持需求扩张与部分设备交付，但供给约束和收入确认节奏仍构成缺口；现阶段只形成待持续验证的研究判断。",
      workbench: {
        formalJudgment: {
          text: "截至证据截止日，人工复核材料支持 AI 基础设施投入扩张与部分系统交付，但尚不足以确认需求已完整传导为可持续收入；正式判断为证据不足，继续验证。",
          rationale: "正式判断仅使用当前冻结快照中的已审核来源陈述与证据关系，不纳入待审核展望。",
          reviewState: "reviewed",
          snapshotId: "RS-2025-06-30-v3",
          reviewedAt: "2025-06-30T22:40:00+08:00",
        },
        mainContradictionFactorId: "F-X-01",
        mainContradictionEvidenceLinkId: "EL-004",
        largestGapFactorId: "F-C-01",
        nextValidationThesisId: "TH-AIC-03",
        selectedFactorId: "F-T-01",
        sourceEvidenceLinkIds: ["EL-001", "EL-002", "EL-004", "EL-003"],
        factorAnalyses: [
          {
            factorId: "F-D-01",
            proposedRole: "candidate",
            timeOrder: "资本开支指引先于交付与收入披露。",
            mechanism: "预算经设备采购形成需求入口。",
            directEvidence: "微软披露支出用于云与 AI 基础设施。",
            alternatives: "常规云扩容也能解释部分支出。",
            differenceExplanation: "不能解释供应约束造成的收入差异。",
            scope: "主要云厂商，2025—2027 年。",
            falsifier: "支出下调或未转化为部署。",
          },
          {
            factorId: "F-T-01",
            proposedRole: "transmission_factor",
            timeOrder: "订单先于交付，交付先于收入确认。",
            mechanism: "逐段连接订单、交付与分部收入。",
            directEvidence: "NVIDIA 同期披露系统交付与分部收入。",
            alternatives: "价格、产品组合或非 AI 业务增长。",
            differenceExplanation: "解释订单强但交付兑现不同的主体。",
            scope: "同一主体、业务口径与可对齐报告期。",
            falsifier: "订单取消、交付延迟或收入来自别的业务。",
          },
          {
            factorId: "F-C-01",
            proposedRole: "constraint",
            timeOrder: "并网周期先于数据中心投产。",
            mechanism: "电力可得性限制设备部署与利用率。",
            directEvidence: "暂无已审核来源直接连接并网与收入。",
            alternatives: "封装、互连供给或客户验收延后。",
            differenceExplanation: "可能解释地区间投产差异。",
            scope: "具体项目、地区与并网窗口。",
            falsifier: "电力到位而投产仍延迟。",
          },
          {
            factorId: "F-X-01",
            proposedRole: "background",
            timeOrder: "投入增长后，相关收入未同步确认。",
            mechanism: "交付、验收滞后切断当期同步关系。",
            directEvidence: "投入扩张，但订单到收入链仍待核对。",
            alternatives: "产品组合、价格或非 AI 业务增长。",
            differenceExplanation: "识别收入确认节奏不同的主体。",
            scope: "可对齐投入、交付与收入的披露主体。",
            falsifier: "交付与同口径收入按期同步兑现。",
          },
        ],
      },
      versionComparison: {
        beforeSnapshotId: "RS-2025-03-31-v2",
        afterSnapshotId: "RS-2025-06-30-v3",
        before: {
          formalConclusion: {
            state: "开放判断",
            text: "需求扩张已有披露支持，但订单、交付与收入尚未形成经审核的传导关系。",
          },
          inputs: [
            {
              id: "DOC-MSFT-FY25Q2",
              kind: "DocumentVersion",
              label: "Microsoft FY2025 Q2 Form 10-Q",
              version: "sec-10q-2025-01-29-v1",
              availableAt: "2025-01-29T20:18:00Z",
            },
            {
              id: "SERIES-NVDA-DC-v2",
              kind: "数据序列",
              label: "NVIDIA Data Center revenue · 截至 FY25 Q4",
              version: "series-nvda-dc-2025-02-26-v2",
              availableAt: "2025-02-26T21:12:00Z",
            },
          ],
          relationships: [
            { id: "EL-CAPEX-01", label: "资本开支 → AI 基础设施投入", role: "支持", reviewState: "已审核" },
            { id: "EL-TRANSMISSION", label: "订单 → 交付 → 分部收入", role: "关系缺失", reviewState: "未形成" },
          ],
          factors: [
            { id: "F-D-01", label: "云厂商资本开支", role: "候选需求因素" },
            { id: "F-T-01", label: "订单到实际交付", role: "待定义" },
          ],
          gaps: [
            { id: "G-CAPEX-PURPOSE", label: "资本开支是否明确用于 AI 基础设施", state: "未解决" },
            { id: "G-REVENUE-CHAIN", label: "订单、交付与分部收入能否同主体对齐", state: "未解决" },
          ],
        },
        after: {
          formalConclusion: {
            state: "证据不足 · 继续验证",
            text: "投入扩张与部分系统交付成立，但尚不足以确认需求已完整传导为可持续收入。",
          },
          inputs: [
            {
              id: "DOC-MSFT-FY25Q3",
              kind: "DocumentVersion",
              label: "Microsoft FY2025 Q3 Form 10-Q",
              version: "sec-10q-2025-04-30-v1",
              availableAt: "2025-04-30T20:18:00Z",
            },
            {
              id: "DOC-NVDA-FY26Q1",
              kind: "DocumentVersion",
              label: "NVIDIA FY2026 Q1 Form 10-Q",
              version: "sec-10q-2025-05-28-v1",
              availableAt: "2025-05-28T20:13:00Z",
            },
            {
              id: "SERIES-NVDA-DC-v3",
              kind: "数据序列",
              label: "NVIDIA Data Center revenue · 截至 FY26 Q1",
              version: "series-nvda-dc-2025-05-28-v3",
              availableAt: "2025-05-28T20:13:00Z",
            },
          ],
          relationships: [
            { id: "EL-002", label: "系统交付 ↔ 分部收入", role: "支持", reviewState: "已审核" },
            { id: "EL-004", label: "可用容量不足 → 收入确认滞后", role: "反面证据", reviewState: "已审核" },
          ],
          factors: [
            { id: "F-D-01", label: "云厂商资本开支", role: "背景条件" },
            { id: "F-T-01", label: "订单到实际交付", role: "传导因素" },
            { id: "F-C-01", label: "容量与并网周期", role: "限制因素" },
          ],
          gaps: [
            { id: "G-CAPEX-PURPOSE", label: "资本开支用于 AI 基础设施", state: "已解决" },
            { id: "G-REVENUE-CHAIN", label: "完整收入传导仍缺连续点时证据", state: "仍未解决" },
            { id: "G-CAPACITY", label: "容量约束影响收入确认的持续期", state: "新增缺口" },
          ],
        },
        changeRail: {
          inputSummary: "新增 2 个 DocumentVersion · 数据序列 v2 → v3 · 6 项未变输入已折叠",
          relationshipSummary: "新增 1 条支持关系与 1 条反面关系，均经人工审核",
          factorSummary: "候选需求因素 → 背景条件；订单交付被定义为传导因素",
          conclusionSummary: "开放判断 → 证据不足 · 继续验证",
          gapSummary: "已解决 1 · 新增 1 · 仍未解决 1",
          rationale: "审核人将需求披露与收入传导拆开判断：新增交付证据只支持局部链条；EL-004 证明可用容量与确认节奏仍会切断即时传导，因此正式结论收敛为“证据不足，继续验证”。",
          reviewedBy: "林岚 · 行业研究",
          reviewedAt: "2025-06-30 22:40 CST",
        },
        aiProposal: {
          runId: "AI-RERUN-2025-07-02-01",
          observedAt: "2025-07-02 08:40 CST",
          label: "未经人工复核",
          text: "新采集的 10-Q 来源确认没有改变数值；模型建议复核传导因素措辞。",
          boundary: "发生在 v3 冻结之后，不属于本次正式快照变更原因；仅可进入下一快照的审核队列。",
        },
      },
    },
    theses: [
      {
        id: "TH-AIC-01",
        origin: "ai",
        evidenceReviewState: "reviewed_links_present",
        observationStart: "2025-01-01",
        observationEnd: "2027-12-31",
        title: "云厂商资本开支形成持续算力需求",
        statement: "主要云厂商已披露的资本开支与 AI 基础设施投入在截止日前保持扩张。",
        supportCondition: "至少两家主要云厂商在正式披露中同时给出资本开支扩张与 AI 基础设施用途。",
        falsifier: "主要云厂商下调相关资本开支，或披露投入未转化为部署。",
        nextValidationEvent: "核对 2025 年第二季度云厂商财报与资本开支指引。",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "TH-AIC-02",
        origin: "ai",
        evidenceReviewState: "no_evidence_links",
        observationStart: "2025-01-01",
        observationEnd: "2027-12-31",
        title: "先进芯片与互连供给决定交付斜率",
        statement: "晶圆、先进封装与高速互连约束影响系统交付节奏，不能仅凭需求推断收入。",
        supportCondition: "供应商披露扩产、交期或产能利用信息，并能与交付指标交叉核对。",
        falsifier: "关键产能快速转为宽松且系统交付没有改善，或约束与交付时点不匹配。",
        nextValidationEvent: "等待先进封装月度营收与交换芯片交付更新。",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "TH-AIC-03",
        origin: "ai",
        evidenceReviewState: "pending_relationship_review",
        observationStart: "2025-01-01",
        observationEnd: "2027-12-31",
        title: "订单到收入的传导需要独立披露验证",
        statement: "只有经审核的订单、交付、收入确认链条，才能支持需求向公司业绩传导。",
        supportCondition: "同一主体的订单或积压、实际交付与分部收入均有点时披露，且口径可对齐。",
        falsifier: "积压订单取消、交付延迟，或相关收入增长主要来自不同业务。",
        nextValidationEvent: "复核下一期分部收入、递延收入与订单履约说明。",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    factors: [
      { id: "F-D-01", group: "demand", label: "云厂商 AI 基础设施资本开支", stance: "support", status: "candidate" },
      { id: "F-S-01", group: "supply", label: "先进封装产能与交期", stance: "constraint", status: "candidate" },
      { id: "F-S-02", group: "supply", label: "高速互连芯片供给", stance: "constraint", status: "candidate" },
      { id: "F-T-01", group: "transmission", label: "订单积压到实际交付", stance: "support", status: "candidate" },
      { id: "F-C-01", group: "constraints", label: "数据中心电力与并网周期", stance: "warning", status: "candidate" },
      { id: "F-A-01", group: "alternatives", label: "自研加速器替代外购 GPU", stance: "alternative", status: "candidate" },
      { id: "F-X-01", group: "contradiction", label: "高投入但相关收入确认滞后", stance: "contradict", status: "candidate" },
    ],
    documents: [
      {
        id: "DOC-MSFT-FY25Q3",
        title: "Microsoft FY2025 Q3 Form 10-Q",
        sourceVersion: "sec-10q-2025-04-30-v1",
        sourceSpan: "pp. 35-39, capital expenditures and cloud infrastructure",
        publishedAt: "2025-04-30T20:10:00Z",
        availableAt: "2025-04-30T20:18:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "DOC-NVDA-FY26Q1",
        title: "NVIDIA FY2026 Q1 Form 10-Q",
        sourceVersion: "sec-10q-2025-05-28-v1",
        sourceSpan: "pp. 22-27, Data Center revenue and supply commitments",
        publishedAt: "2025-05-28T20:05:00Z",
        availableAt: "2025-05-28T20:13:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "DOC-MSFT-FY25Q3-CALL",
        title: "Microsoft FY2025 Q3 earnings call transcript",
        documentType: "业绩说明会",
        sourceName: "Microsoft Investor Relations",
        sourceVersion: "issuer-call-2025-04-30-v1",
        previousVersion: "issuer-call-2025-04-30-v0 · 初始转录",
        sourceSpan: "prepared remarks, pp. 4-5, capacity constraints and revenue timing",
        publishedAt: "2025-04-30T21:30:00Z",
        availableAt: "2025-04-30T21:38:00Z",
        acquiredAt: "2025-04-30T21:44:00Z",
        entities: ["Microsoft", "Azure AI"],
        linkedCaseIds: ["RC-AIC-2025-01", "RC-CLOUD-CAPACITY-2025-02"],
        reuseHistory: [
          { caseId: "RC-AIC-2025-01", label: "AI 算力需求到收入传导", reusedAt: "2025-05-01 09:18" },
          { caseId: "RC-CLOUD-CAPACITY-2025-02", label: "云基础设施供给约束", reusedAt: "2025-05-06 14:32" },
        ],
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "DOC-TSMC-2025M05",
        title: "TSMC May 2025 Monthly Revenue",
        sourceVersion: "ir-monthly-2025-06-10-v1",
        sourceSpan: "table 1, net revenue May 2025",
        publishedAt: "2025-06-10T05:30:00Z",
        availableAt: "2025-06-10T05:35:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "DOC-BRCM-FY25Q2",
        title: "Broadcom FY2025 Q2 earnings release",
        sourceVersion: "ir-release-2025-06-05-v1",
        sourceSpan: "AI revenue outlook paragraph and segment table",
        publishedAt: "2025-06-05T20:15:00Z",
        availableAt: "2025-06-05T20:21:00Z",
        reviewState: "pending_review",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    statements: [
      {
        id: "ST-001",
        documentId: "DOC-MSFT-FY25Q3",
        text: "资本开支继续用于支持云与 AI 基础设施。",
        sourceVersion: "sec-10q-2025-04-30-v1",
        sourceSpan: "p. 38, paragraphs 2-3",
        publishedAt: "2025-04-30T20:10:00Z",
        availableAt: "2025-04-30T20:18:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "ST-002",
        documentId: "DOC-NVDA-FY26Q1",
        text: "数据中心收入增长与 Blackwell 系统交付同时披露。",
        sourceVersion: "sec-10q-2025-05-28-v1",
        sourceSpan: "p. 24, Data Center discussion",
        publishedAt: "2025-05-28T20:05:00Z",
        availableAt: "2025-05-28T20:13:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "ST-003",
        documentId: "DOC-BRCM-FY25Q2",
        text: "AI 相关收入展望上调，但交付与分部口径仍待人工核对。",
        sourceExcerpt: "AI revenue, which came in at $4.4 billion, accelerated to 46% growth year-on-year.",
        sourceVersion: "ir-release-2025-06-05-v1",
        sourceSpan: "outlook paragraph 4",
        publishedAt: "2025-06-05T20:15:00Z",
        availableAt: "2025-06-05T20:21:00Z",
        reviewState: "pending_review",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "ST-004",
        documentId: "DOC-MSFT-FY25Q3-CALL",
        text: "AI 基础设施需求高于可供容量，资本投入需待产能上线后支持收入。",
        sourceExcerpt: "Demand for our AI services remained higher than our available capacity. Capital investments will support growth as new capacity comes online.",
        sourceVersion: "issuer-call-2025-04-30-v1",
        sourceSpan: "prepared remarks, pp. 4-5, capacity constraints and revenue timing",
        publishedAt: "2025-04-30T21:30:00Z",
        availableAt: "2025-04-30T21:38:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    evidenceLinks: [
      {
        id: "EL-001",
        thesisId: "TH-AIC-01",
        statementId: "ST-001",
        role: "support",
        rationale: "披露同时限定投入方向与时间。",
        sourceVersion: "sec-10q-2025-04-30-v1",
        sourceSpan: "p. 38, paragraphs 2-3",
        publishedAt: "2025-04-30T20:10:00Z",
        availableAt: "2025-04-30T20:18:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "EL-002",
        thesisId: "TH-AIC-03",
        statementId: "ST-002",
        role: "support",
        rationale: "订单需求与交付、分部收入具备同主体披露入口，但机制链仍需逐段审核。",
        sourceVersion: "sec-10q-2025-05-28-v1",
        sourceSpan: "p. 24, Data Center discussion",
        publishedAt: "2025-05-28T20:05:00Z",
        availableAt: "2025-05-28T20:13:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "EL-003",
        thesisId: "TH-AIC-03",
        statementId: "ST-003",
        role: "gap",
        rationale: "展望尚不能替代实际交付与收入确认记录。",
        sourceVersion: "ir-release-2025-06-05-v1",
        sourceSpan: "outlook paragraph 4",
        publishedAt: "2025-06-05T20:15:00Z",
        availableAt: "2025-06-05T20:21:00Z",
        reviewState: "pending_review",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "EL-004",
        thesisId: "TH-AIC-03",
        statementId: "ST-004",
        role: "contradict",
        rationale: "需求和资本投入不等同于当期可用容量或收入确认，构成对即时完整传导的反面证据。",
        sourceVersion: "issuer-call-2025-04-30-v1",
        sourceSpan: "prepared remarks, pp. 4-5, capacity constraints and revenue timing",
        publishedAt: "2025-04-30T21:30:00Z",
        availableAt: "2025-04-30T21:38:00Z",
        reviewState: "reviewed",
        reviewedBy: "林岚 · 行业研究",
        reviewedAt: "2025-05-02T10:26:00+08:00",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    metrics: [
      {
        id: "M-NVDA-DC-REV",
        name: "Data Center revenue",
        value: "$39.1bn",
        period: "FY2026 Q1",
        sourceVersion: "sec-10q-2025-05-28-v1",
        sourceSpan: "p. 24, segment revenue table",
        publishedAt: "2025-05-28T20:05:00Z",
        availableAt: "2025-05-28T20:13:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "M-TSMC-M05-YOY",
        name: "May monthly revenue year-on-year change",
        value: "34.8%",
        period: "2025-05",
        sourceVersion: "ir-monthly-2025-06-10-v1",
        sourceSpan: "table 1, net revenue May 2025",
        publishedAt: "2025-06-10T05:30:00Z",
        availableAt: "2025-06-10T05:35:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    companies: [
      {
        id: "CO-NVDA",
        name: "NVIDIA",
        mappingRole: "compute-system-supplier",
        disclosureDate: "2025-05-28",
        sourceVersion: "sec-10q-2025-05-28-v1",
        sourceSpan: "cover and segment note",
        publishedAt: "2025-05-28T20:05:00Z",
        availableAt: "2025-05-28T20:13:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "CO-TSM",
        name: "TSMC",
        mappingRole: "foundry-and-advanced-packaging",
        disclosureDate: "2025-06-10",
        sourceVersion: "ir-monthly-2025-06-10-v1",
        sourceSpan: "issuer and revenue table",
        publishedAt: "2025-06-10T05:30:00Z",
        availableAt: "2025-06-10T05:35:00Z",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
    ],
    funds: [
      {
        id: "FUND-ETF-AI-INFRA",
        name: "示例算力基础设施 ETF",
        mappingRole: "holding-disclosure-only",
        companyId: "CO-NVDA",
        disclosedWeight: "8.4%",
        disclosureDate: "2025-03-31",
        sourceVersion: "fund-report-2025q1-v1",
        sourceSpan: "top ten holdings, row 2",
        publishedAt: "2025-04-21T08:00:00+08:00",
        availableAt: "2025-04-21T08:07:00+08:00",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
        boundary: "持仓披露映射，不构成投资建议。",
      },
      {
        id: "FUND-SEMI-INDEX",
        name: "示例半导体指数基金",
        mappingRole: "holding-disclosure-only",
        companyId: "CO-TSM",
        disclosedWeight: "6.1%",
        disclosureDate: "2025-03-31",
        sourceVersion: "fund-report-2025q1-v2",
        sourceSpan: "top ten holdings, row 5",
        publishedAt: "2025-04-22T08:00:00+08:00",
        availableAt: "2025-04-22T08:06:00+08:00",
        reviewState: "pending_review",
        snapshotMembership: ["RS-2025-06-30-v3"],
        boundary: "待核对份额类别与披露口径，不构成投资建议。",
      },
    ],
    reviewQueue: [
      {
        id: "RQ-001",
        targetId: "ST-003",
        task: "核对 AI 收入口径、对应交付期与分部归属",
        sourceVersion: "ir-release-2025-06-05-v1",
        sourceSpan: "outlook paragraph 4",
        publishedAt: "2025-06-05T20:15:00Z",
        availableAt: "2025-06-05T20:21:00Z",
        reviewState: "pending_review",
        priority: "high",
        snapshotMembership: ["RS-2025-06-30-v3"],
        aiLabel: "AI 草案 · 未经人工复核",
      },
      {
        id: "RQ-002",
        targetId: "FUND-SEMI-INDEX",
        task: "确认基金份额类别与报告期持仓口径",
        sourceVersion: "fund-report-2025q1-v2",
        sourceSpan: "top ten holdings, row 5",
        publishedAt: "2025-04-22T08:00:00+08:00",
        availableAt: "2025-04-22T08:06:00+08:00",
        reviewState: "pending_review",
        priority: "medium",
        snapshotMembership: ["RS-2025-06-30-v3"],
        aiLabel: "AI 草案 · 未经人工复核",
      },
    ],
    snapshots: [
      {
        id: "RS-2025-06-30-v3",
        cutoff: "2025-06-30",
        frozenAt: "2025-06-30T23:59:59+08:00",
        label: "当前冻结快照",
        sourceVersion: "research-case-RC-AIC-2025-01-v3",
        sourceSpan: "complete citation manifest",
        publishedAt: "2025-06-30T23:59:59+08:00",
        availableAt: "2025-06-30T23:59:59+08:00",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-06-30-v3"],
      },
      {
        id: "RS-2025-03-31-v2",
        cutoff: "2025-03-31",
        frozenAt: "2025-04-01T09:12:00+08:00",
        label: "上一季度冻结快照",
        sourceVersion: "research-case-RC-AIC-2025-01-v2",
        sourceSpan: "complete citation manifest",
        publishedAt: "2025-04-01T09:12:00+08:00",
        availableAt: "2025-04-01T09:12:00+08:00",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2025-03-31-v2"],
      },
      {
        id: "RS-2024-12-31-v1",
        cutoff: "2024-12-31",
        frozenAt: "2025-01-02T10:05:00+08:00",
        label: "初始冻结快照",
        sourceVersion: "research-case-RC-AIC-2025-01-v1",
        sourceSpan: "complete citation manifest",
        publishedAt: "2025-01-02T10:05:00+08:00",
        availableAt: "2025-01-02T10:05:00+08:00",
        reviewState: "reviewed",
        snapshotMembership: ["RS-2024-12-31-v1"],
      },
    ],
    providerRuns: [
      { id: "PR-001", provider: "SEC EDGAR", outcome: "success", observedAt: "2025-06-30T18:10:00+08:00", detail: "4 filings normalized" },
      { id: "PR-002", provider: "Issuer IR", outcome: "success", observedAt: "2025-06-30T18:14:00+08:00", detail: "3 releases preserved with source versions" },
      { id: "PR-003", provider: "Market data quota", outcome: "quota_failure", observedAt: "2025-06-30T18:20:00+08:00", detail: "Daily call limit exceeded; no inferred replacement values" },
      { id: "PR-004", provider: "Licensed holdings feed", outcome: "permission_gap", observedAt: "2025-06-30T18:22:00+08:00", detail: "Current credential lacks historical holdings permission" },
      {
        id: "PR-005",
        provider: "Research operations",
        outcome: "manual_upload",
        observedAt: "2025-06-30T18:35:00+08:00",
        sourceVersion: "fund-report-2025q1-v2",
        reviewQueueId: "RQ-002",
        detail: "Fund reports uploaded and queued for review",
      },
    ],
  });
}());
