"""Domain layer for the underwriting bounded context."""

from .answerability import (
    ENTRY_ACTIONS,
    AnswerabilityInput,
    AnswerabilityResult,
    enforce_action_boundary,
    evaluate_answerability,
)

from .types import (
    AnswerabilityState,
    BlockerCode,
    EligibleAction,
    HistoricalBasisInput,
    InvestmentMandateInput,
    LedgerEntryInput,
    LedgerKind,
    ResearchObjectKind,
)
from .metrics import (
    AggregationRule,
    MetricDefinition,
    MetricObservation,
    PeriodSemantics,
    ReconciliationResult,
    SourceRole,
    reconcile,
)
from .mechanisms import (
    Falsifier,
    FinancialMapping,
    MechanismPack,
    MechanismStatus,
)
from .industry import (
    AnswerabilityBlocked,
    IndustryInputs,
    IndustryMetric,
    IndustryMetricCollection,
    IndustryRange,
    IndustryScenario,
    IndustryState,
    ScenarioDriverOverride,
    ScenarioKind,
    ScenarioSpec,
)
from .earnings import (
    CompanyExposure,
    CoreContribution,
    EarningsEngine,
    EarningsReconciliations,
    FourCoreView,
    MetricLineageDependency,
    ResolvedMetricObservation,
    SegmentBridgeReconciliation,
    SegmentEconomics,
    SegmentInputs,
    earnings_engine_content_hash,
    validate_earnings_engine_integrity,
)

__all__ = [
    "ENTRY_ACTIONS",
    "AnswerabilityState",
    "AnswerabilityInput",
    "AnswerabilityResult",
    "BlockerCode",
    "EligibleAction",
    "HistoricalBasisInput",
    "InvestmentMandateInput",
    "LedgerEntryInput",
    "LedgerKind",
    "ResearchObjectKind",
    "enforce_action_boundary",
    "evaluate_answerability",
    "AggregationRule",
    "MetricDefinition",
    "MetricObservation",
    "PeriodSemantics",
    "ReconciliationResult",
    "SourceRole",
    "reconcile",
    "Falsifier",
    "FinancialMapping",
    "MechanismPack",
    "MechanismStatus",
    "IndustryInputs",
    "IndustryMetric",
    "IndustryMetricCollection",
    "IndustryRange",
    "IndustryScenario",
    "IndustryState",
    "ScenarioDriverOverride",
    "ScenarioKind",
    "ScenarioSpec",
    "AnswerabilityBlocked",
    "CompanyExposure",
    "CoreContribution",
    "EarningsEngine",
    "EarningsReconciliations",
    "FourCoreView",
    "MetricLineageDependency",
    "ResolvedMetricObservation",
    "SegmentBridgeReconciliation",
    "SegmentEconomics",
    "SegmentInputs",
    "earnings_engine_content_hash",
    "validate_earnings_engine_integrity",
]
