"""The trusted identity shape exposed to application services."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True, slots=True)
class ResearchPrincipal:
    """One authenticated user, without bearer tokens or raw OIDC claims."""

    user_id: UUID
    issuer: str
    subject: str
    tenant_id: str
    display_name: str
    roles: frozenset[str]
    expires_at: datetime

    @property
    def actor(self) -> str:
        """Stable audit identity generated by the server."""
        return f"user:{self.user_id}"

    @property
    def server_actor(self) -> str:
        """Compatibility name used by existing write services."""
        return self.actor
