import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import { ManualMonitorStart } from '@/workbench/ManualMonitorStart';
const run = { id: 'run', status: 'queued', stage: 'planning', next_action: '等待执行', round: 0, max_rounds: 3, budget: 12, budget_used: 0 };
afterEach(() => { vi.unstubAllGlobals(); sessionStorage.clear(); });
it('requires consent and retries an uncertain request with the same identity', async () => {
  const fetcher = vi.fn().mockRejectedValueOnce(new Error('network')).mockResolvedValue(new Response(JSON.stringify(run)));
  vi.stubGlobal('fetch', fetcher);
  const onStarted = vi.fn();
  render(<ManualMonitorStart caseId="a" actor="研究员" version={2} budget={12} allowedSources={['company_disclosure']} ready onStarted={onStarted} />);
  const button = screen.getByRole('button', { name: '按此计划启动一次研究' });
  expect(button).toBeDisabled();
  await userEvent.type(screen.getByLabelText('单次研究启动原因'), '核验公告');
  await userEvent.click(screen.getByLabelText('我已核对上述范围和额度，确认启动一次研究'));
  await userEvent.click(button);
  await screen.findByRole('alert');
  await userEvent.click(button);
  await screen.findByText('研究已排队，运行编号：run');
  const first = JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));
  const second = JSON.parse(String(fetcher.mock.calls[1]?.[1]?.body));
  expect(first).toEqual(second);
  expect(first.expected_version).toBe(2);
  expect(first.actor).toBe('研究员');
  expect(first.idempotency_key).toBeTruthy();
  expect(onStarted).toHaveBeenCalledOnce();
  expect(button).toBeDisabled();
});
it('blocks starting when any selected protocol is blocked', async () => {
  render(<ManualMonitorStart caseId="a" actor="研究员" version={2} budget={12} allowedSources={[]} ready={false} onStarted={() => {}} />);
  await userEvent.type(screen.getByLabelText('单次研究启动原因'), '核验');
  await userEvent.click(screen.getByLabelText('我已核对上述范围和额度，确认启动一次研究'));
  expect(screen.getByRole('button', { name: '按此计划启动一次研究' })).toBeDisabled();
});
it('freezes uncertain command content even if the parent actor changes', async () => {
  const fetcher = vi.fn().mockRejectedValueOnce(new Error('lost response')).mockResolvedValue(new Response(JSON.stringify(run)));
  vi.stubGlobal('fetch', fetcher);
  const props = { caseId: 'a', version: 2, budget: 12, allowedSources: ['company_disclosure'], ready: true, onStarted: () => {} };
  const view = render(<ManualMonitorStart {...props} actor="原操作人" />);
  await userEvent.type(screen.getByLabelText('单次研究启动原因'), '首次原因');
  await userEvent.click(screen.getByLabelText('我已核对上述范围和额度，确认启动一次研究'));
  await userEvent.click(screen.getByRole('button', { name: '按此计划启动一次研究' }));
  await screen.findByRole('alert');
  expect(screen.getByLabelText('单次研究启动原因')).toBeDisabled();
  view.rerender(<ManualMonitorStart {...props} actor="新操作人" />);
  await userEvent.click(screen.getByRole('button', { name: '按此计划启动一次研究' }));
  await screen.findByText('研究已排队，运行编号：run');
  expect(fetcher.mock.calls[1]?.[1]?.body).toBe(fetcher.mock.calls[0]?.[1]?.body);
});
it('allows correcting content after an explicit validation rejection', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{}', { status: 422 })));
  render(<ManualMonitorStart caseId="a" actor="研究员" version={2} budget={12} allowedSources={[]} ready onStarted={() => {}} />);
  await userEvent.type(screen.getByLabelText('单次研究启动原因'), '原因');
  await userEvent.click(screen.getByLabelText('我已核对上述范围和额度，确认启动一次研究'));
  await userEvent.click(screen.getByRole('button', { name: '按此计划启动一次研究' }));
  await screen.findByRole('alert');
  expect(screen.getByLabelText('单次研究启动原因')).toBeEnabled();
  expect(screen.queryByText(/正在核实首次提交/)).not.toBeInTheDocument();
});
