import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import { MonitorConfiguration } from '@/workbench/MonitorConfiguration';
const detail = { monitor: null, available_confirmed_factors: [{ id: 'f', statement: '订单趋势' }] };
const response = (x: unknown, status = 200) => new Response(JSON.stringify(x), { status });
afterEach(() => vi.unstubAllGlobals());
it('creates a bounded explicit configuration through PUT and verifies it through GET', async () => {
  let saved: unknown = null;
  const fetcher = vi.fn((_url: string, init: RequestInit) => {
    if (init.method === 'PUT') saved = { ...JSON.parse(String(init.body)), id: 'm', version: 1, status: 'active' };
    return Promise.resolve(response(init.method === 'PUT' ? saved : { ...detail, monitor: saved }));
  });
  vi.stubGlobal('fetch', fetcher);
  const onSaved = vi.fn();
  render(<MonitorConfiguration caseId="a" actor="研究员" onSaved={onSaved} />);
  expect(fetcher).not.toHaveBeenCalled();
  await userEvent.click(screen.getByRole('button', { name: '配置监控计划' }));
  await userEvent.click(await screen.findByLabelText('订单趋势'));
  await userEvent.click(screen.getByLabelText('公司披露'));
  await userEvent.type(screen.getByLabelText('下一核验事件'), '下一次财报');
  await userEvent.type(screen.getByLabelText('配置变更原因'), '持续验证');
  expect(screen.getByRole('button', { name: '保存并启用监控' })).toBeDisabled();
  await userEvent.click(screen.getByLabelText('我已核对范围与预算，同意启用未来调度'));
  await userEvent.click(screen.getByRole('button', { name: '保存并启用监控' }));
  await screen.findByText('监控配置已保存，当前版本 1。');
  expect(onSaved).toHaveBeenCalledOnce();
  expect(fetcher.mock.calls.find(([, init]) => init.method === 'PUT')?.[1].body).toBe(JSON.stringify({ actor: '研究员', expected_version: 0, frequency: 'daily_20_00', factor_ids: ['f'], allowed_source_types: ['company_disclosure'], next_verification_event: '下一次财报', budget: 20, change_reason: '持续验证' }));
});
it('does not offer saving without confirmed factors', async () => {
  vi.stubGlobal('fetch', vi.fn(() => Promise.resolve(response({ ...detail, available_confirmed_factors: [] }))));
  render(<MonitorConfiguration caseId="a" actor="研究员" onSaved={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '配置监控计划' }));
  await screen.findByText('暂无可用的已确认因素，请先完成因素审核。');
  expect(screen.getByRole('button', { name: '保存并启用监控' })).toBeDisabled();
});
it('keeps a failed write draft and blocks repeat submission until state is reloaded', async () => {
  const fetcher = vi.fn((_url: string, init: RequestInit) => Promise.resolve(init.method === 'PUT' ? response({}, 503) : response(detail)));
  vi.stubGlobal('fetch', fetcher);
  const saved = vi.fn();
  render(<MonitorConfiguration caseId="a" actor="研究员" onSaved={saved} />);
  await userEvent.click(screen.getByRole('button', { name: '配置监控计划' }));
  await userEvent.click(await screen.findByLabelText('订单趋势'));
  await userEvent.click(screen.getByLabelText('公司披露'));
  await userEvent.type(screen.getByLabelText('下一核验事件'), '财报');
  await userEvent.type(screen.getByLabelText('配置变更原因'), '核验');
  await userEvent.click(screen.getByLabelText('我已核对范围与预算，同意启用未来调度'));
  await userEvent.click(screen.getByRole('button', { name: '保存并启用监控' }));
  await screen.findByRole('alert');
  expect(screen.getByLabelText('配置变更原因')).toHaveValue('核验');
  expect(screen.getByRole('button', { name: '保存并启用监控' })).toBeDisabled();
  expect(saved).not.toHaveBeenCalled();
  expect(fetcher.mock.calls.filter(([, init]) => init.method === 'PUT')).toHaveLength(1);
});
