import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import { ResearchRunPanel } from '@/workbench/ResearchRunPanel';
const run = { id: 'r', status: 'running', stage: 'retrieval', round: 1, max_rounds: 3, budget: 10, budget_used: 2, next_action: '继续执行' };
const detail = { ...run, case_id: 'a', stop_reason: null, gaps: ['缺少公告'], progress: { completed: 1 }, evidence: {} };
const response = (x: unknown, status = 200) => new Response(JSON.stringify(x), { status });
afterEach(() => vi.unstubAllGlobals());
it('loads details lazily, paginates events and confirms cancellation from a fresh read', async () => {
  let cancelled = false;
  const fetcher = vi.fn((url: string, init: RequestInit) => Promise.resolve(response(init.method === 'POST' ? (cancelled = true, { ...run, status: 'cancelled' }) : url.includes('/events') ? { run_id: 'r', items: [{ seq: url.endsWith('=1') ? 2 : 1, created_at: '2026-09-06', message: url.endsWith('=1') ? '第二事件' : '检索开始', details: { actor: '研究员' } }], has_more: !url.endsWith('=1') } : { ...detail, status: cancelled ? 'cancelled' : 'running' })));
  vi.stubGlobal('fetch', fetcher);
  render(<ResearchRunPanel caseId="a" run={run} actor="研究员" onRefresh={() => {}} />);
  expect(fetcher).not.toHaveBeenCalled();
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  await screen.findByText('检索开始');
  await userEvent.click(screen.getByRole('button', { name: '加载更多事件' }));
  await screen.findByText('第二事件');
  await userEvent.type(screen.getByLabelText('取消原因'), '范围变化');
  await userEvent.click(screen.getByRole('button', { name: '确认取消本次运行' }));
  expect(await screen.findByText('本次运行已取消。')).toBeInTheDocument();
  expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeDisabled();
});
it('retains reason on server conflict and refresh can discover a terminal run', async () => {
  let terminal = false;
  vi.stubGlobal('fetch', vi.fn((url: string, init: RequestInit) => Promise.resolve(init.method === 'POST' ? response({}, 409) : response(url.includes('/events') ? { run_id: 'r', items: [], has_more: false } : { ...detail, status: terminal ? 'completed' : 'running' }))));
  render(<ResearchRunPanel caseId="a" run={run} actor="研究员" onRefresh={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  await screen.findByText('缺少公告');
  await userEvent.type(screen.getByLabelText('取消原因'), '原因');
  await userEvent.click(screen.getByRole('button', { name: '确认取消本次运行' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('状态已变化');
  expect(screen.getByLabelText('取消原因')).toHaveValue('原因');
  terminal = true;
  await userEvent.click(screen.getByRole('button', { name: '刷新运行详情' }));
  await waitFor(() => expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeDisabled());
  expect(screen.queryByText('本次运行已取消。')).not.toBeInTheDocument();
});
it('ignores stale responses after run changes', async () => {
  let resolve!: (value: Response) => void;
  vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>((done) => { resolve = done; })));
  const view = render(<ResearchRunPanel caseId="a" run={run} actor="研究员" onRefresh={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  view.rerender(<ResearchRunPanel caseId="b" run={{ ...run, id: 'other' }} actor="研究员" onRefresh={() => {}} />);
  resolve(response({ run_id: 'r', items: [], has_more: false }));
  expect(screen.queryByText('缺少公告')).not.toBeInTheDocument();
});
it('does not announce cancellation success if its authoritative refresh fails', async () => {
  let cancelled = false;
  vi.stubGlobal('fetch', vi.fn((url: string, init: RequestInit) => Promise.resolve(init.method === 'POST' ? (cancelled = true, response({ ...run, status: 'cancelled' })) : cancelled ? response({}, 503) : response(url.includes('/events') ? { run_id: 'r', items: [], has_more: false } : detail))));
  render(<ResearchRunPanel caseId="a" run={run} actor="研究员" onRefresh={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  await screen.findByText('缺少公告');
  await userEvent.type(screen.getByLabelText('取消原因'), '原因');
  await userEvent.click(screen.getByRole('button', { name: '确认取消本次运行' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('暂时不可用');
  expect(screen.queryByText('本次运行已取消。')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeDisabled();
});
it('disables cancellation for unknown terminal states and malformed detail', async () => {
  vi.stubGlobal('fetch', vi.fn((url: string) => Promise.resolve(response(url.includes('/events') ? { run_id: 'r', items: [], has_more: false } : { ...detail, case_id: 'wrong' }))));
  render(<ResearchRunPanel caseId="a" run={{ ...run, status: 'future_terminal' }} actor="研究员" onRefresh={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('数据格式');
  expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeDisabled();
});
it('requires a fresh detail read before cancelling after a refresh error', async () => {
  let fail = false;
  vi.stubGlobal('fetch', vi.fn((url: string) => Promise.resolve(fail ? response({}, 503) : response(url.includes('/events') ? { run_id: 'r', items: [], has_more: false } : detail))));
  render(<ResearchRunPanel caseId="a" run={run} actor="研究员" onRefresh={() => {}} />);
  await userEvent.click(screen.getByRole('button', { name: '查看运行详情' }));
  await screen.findByText('缺少公告');
  await userEvent.type(screen.getByLabelText('取消原因'), '原因');
  expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeEnabled();
  fail = true;
  await userEvent.click(screen.getByRole('button', { name: '刷新运行详情' }));
  await screen.findByRole('alert');
  expect(screen.getByRole('button', { name: '确认取消本次运行' })).toBeDisabled();
});
