/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/research-cases/{case_id}/workbench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workbench
         * @description Return the focused workbench read model for a research case.
         *
         *     The optional ``cutoff`` controls point-in-time visibility of evidence links
         *     and holding disclosures.  When omitted, the current time is used.
         */
        get: operations["workbench_api_research_cases__case_id__workbench_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health V1 */
        get: operations["health_v1_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_research_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-cases/{case_id}/dossier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dossier */
        get: operations["dossier_api_v1_research_cases__case_id__dossier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-cases/{case_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_api_v1_research_cases__case_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Detail */
        get: operations["document_detail_api_v1_documents__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentDTO */
        AssessmentDTO: {
            /** Id */
            id: string;
            /** Thesis Id */
            thesis_id: string;
            /**
             * Conclusion
             * @enum {string}
             */
            conclusion: "supported" | "contradicted" | "insufficient_evidence";
            /** Rationale */
            rationale: string;
            /** Gaps */
            gaps: string[];
            /** Provisional */
            provisional: boolean;
            review: components["schemas"]["ReviewDecisionDTO"] | null;
        };
        /** CaseListResponse */
        CaseListResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            /** Items */
            items: components["schemas"]["CaseSummaryDTO"][];
            page: components["schemas"]["CursorPage"];
        };
        /** CaseSummaryDTO */
        CaseSummaryDTO: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** CausalStepDTO */
        CausalStepDTO: {
            /** Id */
            id: string;
            /** Sequence */
            sequence: number;
            /** Description */
            description: string;
        };
        /** CursorPage */
        CursorPage: {
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            document: components["schemas"]["DocumentSummaryDTO"];
            /** Spans */
            spans: components["schemas"]["SourceSpanDTO"][];
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            basis: components["schemas"]["HistoricalBasisDTO"];
            /** Items */
            items: components["schemas"]["DocumentSummaryDTO"][];
            page: components["schemas"]["CursorPage"];
        };
        /** DocumentSummaryDTO */
        DocumentSummaryDTO: {
            /** Id */
            id: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Source Url */
            source_url: string;
            /** Published At */
            published_at: string | null;
            /** Available At */
            available_at: string;
            /** Acquired At */
            acquired_at: string;
            /** Parser Version */
            parser_version: string;
            /** Supersedes Id */
            supersedes_id: string | null;
            /** Span Count */
            span_count: number;
            /** Statement Count */
            statement_count: number;
            /**
             * Parse State
             * @enum {string}
             */
            parse_state: "parsed" | "unparsed";
        };
        /** DossierResponse */
        DossierResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            basis: components["schemas"]["HistoricalBasisDTO"];
            case: components["schemas"]["CaseSummaryDTO"];
            /** Theses */
            theses: components["schemas"]["ThesisSummaryDTO"][];
            /** Focus Thesis Id */
            focus_thesis_id: string;
            assessment: components["schemas"]["AssessmentDTO"] | null;
            /** Causal Chain */
            causal_chain: components["schemas"]["CausalStepDTO"][];
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["EvidenceRecordDTO"][];
            };
            /** Competitive Explanations */
            competitive_explanations: string[];
            /** Gaps */
            gaps: string[];
        };
        /** EvidenceRecordDTO */
        EvidenceRecordDTO: {
            /** Link Id */
            link_id: string;
            /** Statement Id */
            statement_id: string;
            /** Statement Text */
            statement_text: string | null;
            /** Statement Kind */
            statement_kind: string | null;
            /** Span Id */
            span_id: string | null;
            /** Verbatim Text */
            verbatim_text: string | null;
            /** Locator */
            locator: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @enum {string}
             */
            role: "supports" | "contradicts" | "contextualizes";
            /** Reason */
            reason: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Observed Period */
            observed_period: string | null;
            /** Available At */
            available_at: string;
            /** Review State */
            review_state: string;
        };
        /** GraphEdgeDTO */
        GraphEdgeDTO: {
            /** Id */
            id: string;
            /** Semantic Kind */
            semantic_kind: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Review State */
            review_state?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Valid Interval */
            valid_interval?: {
                [key: string]: string | null;
            } | null;
            /** Source Refs */
            source_refs?: string[];
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** GraphNodeDTO */
        GraphNodeDTO: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** GraphPathDTO */
        GraphPathDTO: {
            /** Node Ids */
            node_ids: string[];
            /** Edge Ids */
            edge_ids: string[];
            /** Label */
            label: string;
        };
        /** GraphResponse */
        GraphResponse: {
            /**
             * Schema Version
             * @default graph/v1
             * @constant
             */
            schema_version: "graph/v1";
            basis: components["schemas"]["HistoricalBasisDTO"];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeDTO"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeDTO"][];
            /** Paths */
            paths: components["schemas"]["GraphPathDTO"][];
            page: components["schemas"]["CursorPage"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
        };
        /** HistoricalBasisDTO */
        HistoricalBasisDTO: {
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Is Historical */
            is_historical: boolean;
            /** Ledger High Watermark */
            ledger_high_watermark?: string | null;
            /** Projection Built At */
            projection_built_at?: string | null;
            /** Projection Schema Version */
            projection_schema_version?: string | null;
        };
        /** KeyChangeDTO */
        KeyChangeDTO: {
            /** Id */
            id: string;
            /**
             * Tag
             * @enum {string}
             */
            tag: "新增" | "更新" | "风险" | "缺口";
            /** Text */
            text: string;
            /** Occurred At */
            occurred_at: string;
            /** Source Label */
            source_label: string;
            /** Review State */
            review_state: ("machine_generated" | "reviewed" | "rejected") | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            basis: components["schemas"]["HistoricalBasisDTO"];
            case: components["schemas"]["CaseSummaryDTO"];
            /** Thesis */
            thesis: {
                [key: string]: unknown;
            } | null;
            assessment: components["schemas"]["AssessmentDTO"] | null;
            /** Key Changes */
            key_changes: components["schemas"]["KeyChangeDTO"][];
            /** Framework */
            framework: {
                [key: string]: unknown;
            }[];
            totals: components["schemas"]["OverviewTotalsDTO"];
            /** Task Queue */
            task_queue: {
                [key: string]: unknown;
            }[];
            /** Evidence Changes */
            evidence_changes: {
                [key: string]: unknown;
            }[];
            /** Activity */
            activity: {
                [key: string]: unknown;
            }[];
        };
        /** OverviewTotalsDTO */
        OverviewTotalsDTO: {
            /** Evidence Total */
            evidence_total: number;
            /** Pending Review */
            pending_review: number;
            /** Major Gaps */
            major_gaps: number;
        };
        /** ReviewDecisionDTO */
        ReviewDecisionDTO: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "confirmed" | "modified" | "rejected";
            /** Conclusion */
            conclusion: string | null;
            /** Reason */
            reason: string;
            /** Reviewer */
            reviewer: string;
            /** Reviewed At */
            reviewed_at: string;
        };
        /** SearchGroupDTO */
        SearchGroupDTO: {
            /** Object Type */
            object_type: string;
            /** Hits */
            hits: components["schemas"]["SearchHitDTO"][];
        };
        /** SearchHitDTO */
        SearchHitDTO: {
            /**
             * Object Type
             * @enum {string}
             */
            object_type: "case" | "thesis" | "evidence" | "company" | "stock" | "fund";
            /** Object Id */
            object_id: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Case Id */
            case_id: string | null;
            /** Review State */
            review_state: string | null;
            /** Available At */
            available_at: string | null;
            /** Deep Link */
            deep_link: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            basis: components["schemas"]["HistoricalBasisDTO"];
            /** Groups */
            groups: components["schemas"]["SearchGroupDTO"][];
            page: components["schemas"]["CursorPage"];
        };
        /** SourceSpanDTO */
        SourceSpanDTO: {
            /** Id */
            id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
            /** Verbatim Text */
            verbatim_text: string;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[];
        };
        /** ThesisSummaryDTO */
        ThesisSummaryDTO: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            error: components["schemas"]["ErrorBody"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    workbench_api_research_cases__case_id__workbench_get: {
        parameters: {
            query?: {
                cutoff?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_cases_api_v1_research_cases_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dossier_api_v1_research_cases__case_id__dossier_get: {
        parameters: {
            query?: {
                thesis_id?: string | null;
                cutoff?: string | null;
                research_mode?: boolean;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_v1_research_cases__case_id__graph_get: {
        parameters: {
            query?: {
                thesis_id?: string | null;
                cutoff?: string | null;
                focus?: string | null;
                depth?: number;
                limit?: number;
                research_mode?: boolean;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                q?: string | null;
                cutoff?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_detail_api_v1_documents__version_id__get: {
        parameters: {
            query?: {
                research_mode?: boolean;
            };
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                types?: string | null;
                cutoff?: string | null;
                limit?: number;
                research_mode?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query: {
                case_id: string;
                cutoff?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
