import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, useParams } from "react-router-dom";

import { researchOsApi, type FundExposure, type Graph, type MonitorDetail } from "../../app/researchOsApi";
import { researchClient } from "../../data/researchClient";
import type { EventResearchClient, EventWorkbench } from "../../domain/eventResearch";

const tabs = [["", "研究结论"], ["review", "证据审核"], ["wiki", "Case Wiki"], ["market", "市场与表达"], ["monitor", "监测与运行"]] as const;

function CaseFrame({ children }: { children: (workbench: EventWorkbench, caseId: string) => ReactNode }) {
  const { caseId = "" } = useParams();
  const [data, setData] = useState<EventWorkbench | null>(null);
  useEffect(() => { if (caseId) researchClient.getEventWorkbench(caseId).then(setData).catch(() => setData(null)); }, [caseId]);
  if (!data) return <main className="ros-page"><div className="ros-empty">正在读取 Case；若无权限或 Case 不存在，系统不会展示替代数据。</div></main>;
  return <main className="ros-page ros-case-page">
    <header className="ros-case-header"><p className="ros-eyebrow">ResearchCase v{data.scope.version} · {data.event.ticker || "未绑定股票"}</p><h1>{data.event.eventTitle}</h1><p>{data.lifecycle.summary}</p><div className="ros-case-header__facts"><span>已审核证据 {data.progress.verified}</span><span>待审核 {data.progress.pending}</span><span>无效来源 {data.progress.invalidSource}</span><span>{data.lifecycle.activeRunId ? "运行记录可查看" : "无后台运行"}</span></div></header>
    <nav className="ros-case-tabs" aria-label="Case 页面">{tabs.map(([suffix, label]) => <NavLink key={suffix} end={suffix === ""} to={`/events/${caseId}${suffix ? `/${suffix}` : ""}`}>{label}</NavLink>)}</nav>
    {children(data, caseId)}
  </main>;
}

function FactorList({ data }: { data: EventWorkbench }) {
  return <section className="ros-factor-list"><p className="ros-eyebrow">关键因素与验证缺口</p>{data.factors.map((factor) => <article className="ros-factor-row" key={factor.position}><span>{String(factor.position).padStart(2, "0")}</span><div><strong>{factor.statement}</strong><small>已审核支持 {factor.reviewedSupportCount} · 反证 {factor.reviewedContradictionCount} · AI 待审 {factor.pendingProposalCount}</small>{factor.currentGap && <em>还缺：{factor.currentGap}</em>}</div></article>)}</section>;
}

export function CaseConclusionPage() {
  return <CaseFrame>{(data, caseId) => <section className="ros-case-columns">
    <div><article className="ros-panel ros-panel--conclusion"><p className="ros-eyebrow">当前判断 · {data.conclusion.state === "published" ? "已人工发布" : data.conclusion.state === "ai_draft" ? "AI 草案，未发布" : "暂不下结论"}</p><h2>{data.conclusion.text}</h2><p className="ros-conclusion-text">{data.conclusion.state === "published" ? "该版本只基于已审核资料；新运行只会追加待审证据，不会自动重写结论。" : "尚未审核的候选、二手转述和无授权材料都不会自动进入当前判断。"}</p></article><FactorList data={data} /></div>
    <aside className="ros-case-rail"><section className="ros-action-card"><p className="ros-eyebrow">下一步</p><h2>{data.nextAction.label}</h2><p>{data.lifecycle.currentGap || "先完成当前人工判断，再决定是否创建新的结论或范围版本。"}</p><Link className="ros-button ros-button--primary" to={`/events/${caseId}/${data.nextAction.kind === "review_evidence" || data.nextAction.kind === "review_conclusion" ? "review" : "monitor"}`}>{data.nextAction.kind.includes("review") ? "进入审核" : "查看持续研究"}</Link></section><section className="ros-rail-section"><p className="ros-eyebrow">持续研究</p><h2>{data.lifecycle.activeRunId ? "系统正在受控补证" : "等待下一验证事件"}</h2><p>范围版本 v{data.scope.version} · 仅允许来源内的材料可进入后续审核。</p><Link to={`/events/${caseId}/monitor`}>查看运行记录 →</Link></section><section className="ros-rail-section"><p className="ros-eyebrow">结论依据</p><p>{data.conclusion.citations.length} 条可回溯引用；每条都保留原文定位、可用时点与审核状态。</p></section></aside>
  </section>}</CaseFrame>;
}

export function CaseReviewPage() { return <CaseFrame>{(_data, caseId) => <ReviewContent caseId={caseId} />}</CaseFrame>; }
function ReviewContent({ caseId }: { caseId: string }) {
  const [queue, setQueue] = useState<Awaited<ReturnType<EventResearchClient["getEventReviewQueue"]>> | null>(null);
  useEffect(() => { researchClient.getEventReviewQueue(caseId).then(setQueue).catch(() => setQueue(null)); }, [caseId]);
  if (!queue) return <div className="ros-empty ros-page-gap">正在读取待审核证据；不可访问的来源不会进入审核动作。</div>;
  return <section className="ros-review-workbench"><header className="ros-section-heading"><div><p className="ros-eyebrow">人工审核</p><h2>{queue.summary.pending} 条待审核关系</h2></div><span className="ros-muted">候选仅供核对；不会自动采纳</span></header>{queue.items.length === 0 ? <div className="ros-empty">当前没有待审核候选。</div> : queue.items.map((item) => <article className="ros-review-item" key={item.proposalId}><div><span className="ros-pill ros-pill--human">未经人工复核</span><h3>{item.thesisStatement || "未关联关键因素"}</h3><blockquote>{item.verbatimText || item.statementText || "未抽取到可定位原文"}</blockquote></div><dl><div><dt>原文定位</dt><dd>{JSON.stringify(item.locator)}</dd></div><div><dt>可用时点</dt><dd>{item.availableAt || "未记录"}</dd></div><div><dt>来源与许可</dt><dd>{item.sourceStatusReason}</dd></div></dl><div className="ros-review-actions"><span>{item.aiRole || "候选关系"} · {item.proposalReason}</span><button className="ros-button ros-button--secondary" type="button">查看冻结原文</button></div></article>)}</section>;
}

export function CaseWikiPage() { return <CaseFrame>{(_data, caseId) => <WikiContent caseId={caseId} />}</CaseFrame>; }
function WikiContent({ caseId }: { caseId: string }) {
  const [graph, setGraph] = useState<Graph | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showCandidates, setShowCandidates] = useState(true);
  useEffect(() => { researchOsApi.graph(caseId).then((value) => { setGraph(value); setSelectedId(value.nodes[0]?.id ?? null); }).catch(() => setGraph(null)); }, [caseId]);
  if (!graph) return <div className="ros-empty ros-page-gap">Case Wiki 暂无可读取图谱。系统不会以示例节点替代真实证据。</div>;
  const candidateNode = (node: Graph["nodes"][number]) => node.kind === "proposal" || node.properties?.review_state === "machine_generated";
  const nodes = graph.nodes.filter((node) => showCandidates || !candidateNode(node));
  const selected = nodes.find((node) => node.id === selectedId) || nodes[0];
  const selectedEdges = graph.edges.filter((edge) => edge.source === selected?.id || edge.target === selected?.id);
  const reviewed = graph.edges.filter((edge) => edge.review_state !== "machine_generated").length;
  const candidates = graph.edges.filter((edge) => edge.review_state === "machine_generated").length;
  return <section className="ros-wiki"><header className="ros-section-heading"><div><p className="ros-eyebrow">Case Wiki · 证据关系</p><h2>从资料到基金表达的可追溯路径</h2></div><button className="ros-button ros-button--secondary" type="button" onClick={() => setShowCandidates((value) => !value)}>{showCandidates ? `隐藏 AI 候选 ${candidates}` : `显示 AI 候选 ${candidates}`}</button></header><div className="ros-wiki-grid"><div className="ros-wiki-wrap"><div className="ros-wiki-bar"><span>已审核关系 {reviewed}</span><span>实线：已审核 · 虚线：未经人工复核</span></div><div className="ros-wiki-canvas" aria-label="Case Wiki 节点列表">{nodes.map((node) => <button type="button" onClick={() => setSelectedId(node.id)} className={`ros-wiki-node ros-wiki-node--${node.kind}${node.id === selected?.id ? " is-selected" : ""}${candidateNode(node) ? " is-candidate" : ""}`} key={node.id}><span>{node.kind}</span><strong>{node.label}</strong><small>{candidateNode(node) ? "AI 候选，未进入结论" : "已进入 Case 图谱"}</small></button>)}</div></div><aside className="ros-wiki-inspector">{selected ? <><span className={`ros-pill ${candidateNode(selected) ? "ros-pill--human" : "ros-pill--system"}`}>{candidateNode(selected) ? "未经人工复核" : "已审核对象"}</span><h3>{selected.label}</h3><p>{selected.kind} · {selectedEdges.length} 条关联关系</p><dl>{Object.entries(selected.properties || {}).slice(0, 4).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><div className="ros-legend"><span>关系：{selectedEdges.map((edge) => edge.semantic_kind).join("、") || "暂无"}</span><span>AI 候选不继承结论、市场表达或基金暴露。</span></div></> : <p>选择一个节点以查看其证据与关系。</p>}</aside></div></section>;
}

export function CaseMarketPage() { return <CaseFrame>{(data, caseId) => <MarketContent caseId={caseId} data={data} />}</CaseFrame>; }
function MarketContent({ caseId, data }: { caseId: string; data: EventWorkbench }) {
  const [exposure, setExposure] = useState<FundExposure | null>(null);
  useEffect(() => { researchOsApi.exposure(caseId).then(setExposure).catch(() => setExposure(null)); }, [caseId]);
  return <section className="ros-market"><header className="ros-section-heading"><div><p className="ros-eyebrow">市场与表达</p><h2>把研报判断落到可验证的市场表达</h2></div><span className="ros-pill ros-pill--system">仅展示已披露持仓</span></header><p className="ros-market-intro">先验证关键因素，再分别观察基本面、股票市场和基金披露暴露。它们相关，但不是同一种证据。</p><div className="ros-market-workbench"><section className="ros-market-factors"><p className="ros-eyebrow">关键因素验证</p>{data.factors.map((factor) => <article className="ros-market-factor" key={factor.position}><i className={factor.reviewedContradictionCount > 0 ? "is-risk" : factor.currentGap ? "is-gap" : ""} /><div><strong>{factor.statement}</strong><small>支持 {factor.reviewedSupportCount} · 反证 {factor.reviewedContradictionCount} · 待核对 {factor.pendingProposalCount}</small></div><span>{factor.reviewedContradictionCount > 0 ? "存在反证" : factor.currentGap ? "证据缺口" : "持续验证"}</span></article>)}</section><section className="ros-market-chain"><p className="ros-eyebrow">影响路径</p><div className="ros-chain-row"><article><span>研报主张</span><b>当前 Case 判断</b><small>只引用已审核证据</small></article><i>→</i><article><span>关键因素</span><b>可验证指标</b><small>支持 / 反证 / 缺口</small></article><i>→</i><article><span>公司 / 股票</span><b>基本面与市场观测</b><small>不自动归因</small></article><i>→</i><article><span>基金披露</span><b>报告期内暴露</b><small>非实时仓位</small></article></div><p className="ros-note">股票事件窗口是观测结果；只有时点、机制和反证都足够时，才可以形成有限且带条件的判断。</p></section><aside className="ros-market-rail"><p className="ros-eyebrow">基金披露暴露</p><h2>{exposure ? `截至 ${exposure.as_of}` : "暂无可用披露"}</h2>{!exposure ? <p>当前 Case 尚未绑定已审核公司关系，或没有可访问的基金披露数据。</p> : exposure.funds.map((fund) => <article className="ros-fund-row" key={fund.fund_id}><strong>{fund.fund_name} <small>{fund.fund_code}</small></strong><span>主题暴露 {(fund.theme_exposure * 100).toFixed(2)}%</span>{fund.positions.map((position) => <small key={position.stock_id}>{position.stock_name} · {(position.weight * 100).toFixed(2)}% · {position.report_period}</small>)}</article>)}<p className="ros-market-warning">披露暴露按报告期、披露日和采集日理解，不表示实时持仓，也不构成交易建议。</p></aside></div></section>;
}

type RunEvent = { seq: number; stage: string | null; status: string | null; message: string | null; details: Record<string, unknown>; createdAt?: string };
export function CaseMonitorPage() { return <CaseFrame>{(data, caseId) => <MonitorContent caseId={caseId} activeRunId={data.lifecycle.activeRunId} />}</CaseFrame>; }
function MonitorContent({ caseId, activeRunId }: { caseId: string; activeRunId: string | null }) {
  const [detail, setDetail] = useState<MonitorDetail | null>(null);
  const [events, setEvents] = useState<RunEvent[]>([]);
  const [drawer, setDrawer] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { researchOsApi.monitor(caseId).then(setDetail).catch(() => setError("监控配置尚不可用。")); if (activeRunId) researchOsApi.runEvents(activeRunId).then((response) => setEvents(response.items.map((event) => ({ seq: event.seq, stage: event.stage ?? null, status: event.status ?? null, message: event.message ?? null, details: event.details ?? {}, createdAt: event.created_at })))).catch(() => undefined); }, [caseId, activeRunId]);
  const run = detail?.latest_run;
  return <section className="ros-monitor"><header className="ros-section-heading"><div><p className="ros-eyebrow">监控与版本</p><h2>每一次运行均可检查、复现与配置</h2></div><button className="ros-button ros-button--secondary" type="button" onClick={() => setDrawer(true)}>打开运行详情</button></header>{error && <p className="ros-error">{error}</p>}<div className="ros-monitor-grid"><section className="ros-card ros-run-card"><header className="ros-card-head"><div><p className="ros-eyebrow">{run ? "最近一次运行" : "尚未开始运行"}</p><h2>{run ? `${run.stage} · ${run.status}` : "先配置持续研究"}</h2></div><span>{run ? `更新于 ${run.updated_at}` : ""}</span></header><div className="ros-run-summary"><strong>{events.length ? "系统的每一步都在记录" : "运行将从范围冻结开始记录"}</strong><p>{events.length ? "查看每个阶段的输入、允许来源、排除理由和输出；系统不会在后台悄悄改写结论。" : "立即运行或定时任务都会绑定有效的 CaseMonitor 配置版本。"}</p></div><ol className="ros-run-log">{events.length ? events.map((event) => <li key={event.seq}><span>{event.seq}</span><div><strong>{event.stage || "运行阶段"} · {event.status || "已记录"}</strong><p>{event.message || "无文字摘要"}</p><small>{Object.entries(event.details).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join("、") : String(value)}`).join(" · ")}</small></div></li>) : <li><span>1</span><div><strong>等待运行</strong><p>尚无结构化运行事件；新运行会从读取并冻结配置开始逐条记录。</p></div></li>}</ol></section><aside className="ros-monitor-config"><section className="ros-panel"><p className="ros-eyebrow">当前 CaseMonitor · {detail?.monitor ? `配置 v${detail.monitor.version}` : "未配置"}</p><h2>监控配置</h2><p>每次运行都绑定此版本。之后的改动只创建新版本，过去运行仍可回放。</p>{detail?.monitor ? <dl className="ros-definition"><div><dt>运行频率</dt><dd>{detail.monitor.frequency}</dd></div><div><dt>允许来源</dt><dd>{detail.monitor.allowed_source_types.join("、")}</dd></div><div><dt>下一验证</dt><dd>{detail.monitor.next_verification_event}</dd></div><div><dt>单次上限</dt><dd>{detail.monitor.budget} 份候选资料</dd></div></dl> : <div className="ros-empty ros-empty--compact">尚未设置监控条件。</div>}<Link className="ros-button ros-button--primary" to={`/events/${caseId}/monitor/config`}>调整配置</Link></section><p className="ros-rulebox"><b>可复现要求：</b>触发人/原因、配置版本、查询口径、来源许可、资料版本、阶段输出、排除理由和失败原因均要可查看。</p></aside></div>{drawer && <RunDrawer run={run} detail={detail} events={events} onClose={() => setDrawer(false)} />}</section>;
}

function RunDrawer({ run, detail, events, onClose }: { run: MonitorDetail["latest_run"] | undefined | null; detail: MonitorDetail | null; events: RunEvent[]; onClose: () => void }) { return <aside className="ros-run-drawer" aria-label="运行详情"><header><div><p className="ros-eyebrow">ResearchRun · {run?.id || "尚无运行"}</p><h2>{run ? `${run.stage} · ${run.status}` : "运行详情"}</h2><p>{detail?.monitor ? `CaseMonitor 配置 v${detail.monitor.version} · 可复现` : "尚未绑定配置版本"}</p></div><button aria-label="关闭运行详情" type="button" onClick={onClose}>×</button></header><div className="ros-drawer-body"><section className="ros-run-scope"><p className="ros-eyebrow">本次运行口径</p><dl><div><dt>范围</dt><dd>{detail?.confirmed_factors.map((factor) => factor.statement).join("、") || "未配置"}</dd></div><div><dt>允许来源</dt><dd>{detail?.monitor?.allowed_source_types.join("、") || "未配置"}</dd></div><div><dt>配置版本</dt><dd>{detail?.monitor ? `v${detail.monitor.version}` : "未配置"}</dd></div><div><dt>运行事件</dt><dd>{events.length} 条</dd></div></dl></section><ol className="ros-run-log">{events.map((event) => <li key={event.seq}><span>{event.seq}</span><div><strong>{event.stage || "阶段"}</strong><p>{event.message || "无文字摘要"}</p></div></li>)}</ol></div></aside>; }

export function MonitorConfigPage() { return <CaseFrame>{(_data, caseId) => <MonitorConfigForm caseId={caseId} />}</CaseFrame>; }
function MonitorConfigForm({ caseId }: { caseId: string }) {
  const [detail, setDetail] = useState<MonitorDetail | null>(null); const [selected, setSelected] = useState<string[]>([]); const [frequency, setFrequency] = useState("weekday_08_30"); const [sources, setSources] = useState<string[]>(["licensed_provider"]); const [nextEvent, setNextEvent] = useState(""); const [budget, setBudget] = useState(20); const [reason, setReason] = useState("调整监控范围"); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { researchOsApi.monitor(caseId).then((value) => { setDetail(value); setSelected(value.monitor?.factor_ids ?? value.confirmed_factors.map((factor) => factor.id)); setFrequency(value.monitor?.frequency ?? "weekday_08_30"); setSources(value.monitor?.allowed_source_types ?? ["licensed_provider"]); setNextEvent(value.monitor?.next_verification_event ?? ""); setBudget(value.monitor?.budget ?? 20); }).catch(() => setMessage("无法读取当前可确认因素。")); }, [caseId]);
  const toggleFactor = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); const toggleSource = (source: string) => setSources((current) => current.includes(source) ? current.filter((value) => value !== source) : [...current, source]);
  async function save() { if (!selected.length || !sources.length || !nextEvent.trim() || !reason.trim()) { setMessage("请选择至少一个已确认因素、一个允许来源，并说明下一验证事件与变更原因。"); return; } try { const saved = await researchOsApi.saveMonitor(caseId, { actor: "human:researcher", frequency, factor_ids: selected, allowed_source_types: sources as ("licensed_provider" | "company_disclosure" | "uploaded_file" | "pasted_snapshot")[], next_verification_event: nextEvent, budget, change_reason: reason }); setMessage(`已保存监控版本 v${saved.version}；此前版本保持不变。`); } catch { setMessage("保存失败，未写入任何配置版本。"); } }
  return <section className="ros-panel ros-config"><p className="ros-eyebrow">配置监控</p><h2>调整后会创建新的可复现版本</h2><p>系统只使用这里明确允许的来源和已确认因素；立即补证与定时运行都引用同一版本。</p>{!detail ? <div className="ros-empty ros-empty--compact">正在读取可配置因素…</div> : <div className="ros-config-form"><fieldset><legend>已确认关键因素</legend>{detail.confirmed_factors.map((factor) => <label key={factor.id}><input type="checkbox" checked={selected.includes(factor.id)} onChange={() => toggleFactor(factor.id)} />{factor.statement}</label>)}</fieldset><label>频率<select value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="weekday_08_30">工作日 08:30</option><option value="weekday_12_30">工作日 12:30</option><option value="daily_20_00">每日 20:00</option></select></label><fieldset><legend>允许来源</legend>{[["licensed_provider", "授权数据源"], ["company_disclosure", "公司披露"], ["uploaded_file", "人工上传"], ["pasted_snapshot", "粘贴快照"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={sources.includes(value)} onChange={() => toggleSource(value)} />{label}</label>)}</fieldset><label>下一验证事件<input value={nextEvent} onChange={(event) => setNextEvent(event.target.value)} placeholder="例如：2026Q1 财报披露" /></label><label>检索预算<input type="number" min="1" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><label>变更原因<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="ros-button ros-button--primary" type="button" onClick={save}>保存为新监控版本</button></div>}{message && <p className={message.startsWith("已保存") ? "ros-success" : "ros-error"}>{message}</p>}<Link className="ros-button ros-button--secondary" to={`/events/${caseId}/monitor`}>返回运行记录</Link></section>;
}
