import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, useParams } from "react-router-dom";

import { researchOsApi, type FundExposure, type Graph, type MonitorDetail } from "../../app/researchOsApi";
import { researchClient } from "../../data/researchClient";
import type { EventResearchClient, EventWorkbench } from "../../domain/eventResearch";
import type { DocumentSpan, SourceDocumentView } from "../../domain/types";
import { MarketExpressionContent } from "./MarketExpressionContent";

const tabs = [["", "研究结论"], ["evidence", "命题与证据"], ["documents", "原文资料"], ["review", "证据审核"], ["wiki", "Case Wiki"], ["market", "市场与表达"], ["monitor", "监测与运行"]] as const;

function CaseFrame({ children }: { children: (workbench: EventWorkbench, caseId: string) => ReactNode }) {
  const { caseId = "" } = useParams();
  const [data, setData] = useState<EventWorkbench | null>(null);
  const [loadError, setLoadError] = useState(false);
  const [reload, setReload] = useState(0);
  useEffect(() => { if (!caseId) return; setData(null); setLoadError(false); researchClient.getEventWorkbench(caseId).then(setData).catch(() => setLoadError(true)); }, [caseId, reload]);
  if (!data) return <main className="ros-page"><div className="ros-empty">{loadError ? <><strong>无法读取这个 Case</strong><p>没有展示替代数据；请检查权限、网络或 Case 标识。</p><button className="ros-button ros-button--secondary" type="button" onClick={() => setReload((value) => value + 1)}>重试</button></> : "正在读取 Case；若无权限或 Case 不存在，系统不会展示替代数据。"}</div></main>;
  return <main className="ros-page ros-case-page">
    <header className="ros-case-header"><p className="ros-eyebrow">ResearchCase v{data.scope.version} · {data.event.ticker || "未绑定股票"}</p><h1>{data.event.eventTitle}</h1><p>{data.lifecycle.summary}</p><div className="ros-case-header__facts"><span>已审核证据 {data.progress.verified}</span><span>待审核 {data.progress.pending}</span><span>无效来源 {data.progress.invalidSource}</span><span>{data.lifecycle.activeRunId ? "运行记录可查看" : "无后台运行"}</span></div></header>
    <nav className="ros-case-tabs" aria-label="Case 页面">{tabs.map(([suffix, label]) => <NavLink key={suffix} end={suffix === ""} to={`/events/${caseId}${suffix ? `/${suffix}` : ""}`}>{label}</NavLink>)}</nav>
    {children(data, caseId)}
  </main>;
}

function FactorList({ data }: { data: EventWorkbench }) {
  return <section className="ros-factor-list"><p className="ros-eyebrow">关键因素与验证缺口</p>{data.factors.map((factor) => <article className="ros-factor-row" key={factor.position}><span>{String(factor.position).padStart(2, "0")}</span><div><strong>{factor.statement}</strong><small>已审核支持 {factor.reviewedSupportCount} · 反证 {factor.reviewedContradictionCount} · AI 待审 {factor.pendingProposalCount}</small>{factor.currentGap && <em>还缺：{factor.currentGap}</em>}</div></article>)}</section>;
}

export function CaseEvidencePage() { return <CaseFrame>{(data, caseId) => <section className="ros-evidence-page"><header className="ros-section-heading"><div><p className="ros-eyebrow">命题与证据</p><h2>每一条关系都保留原文、时点与审核边界</h2></div><Link className="ros-button ros-button--secondary" to={`/events/${caseId}/documents`}>原文资料</Link></header><FactorList data={data} /><section className="ros-evidence-list"><p className="ros-eyebrow">已关联资料</p>{data.evidence.length === 0 ? <div className="ros-empty">当前没有可展示的关联资料；未审核候选不会被写成正式依据。</div> : data.evidence.map((evidence, index) => <article className="ros-evidence-row" key={`${evidence.factorStatement}-${index}`}><div><span className={`ros-pill ${evidence.reviewState === "reviewed" ? "ros-pill--system" : "ros-pill--human"}`}>{evidence.reviewState === "reviewed" ? "已审核关系" : "AI 候选，未经复核"}</span><h3>{evidence.factorStatement}</h3><blockquote>{evidence.excerpt}</blockquote></div><dl><div><dt>关系角色</dt><dd>{evidence.role}</dd></div><div><dt>精确定位</dt><dd>{JSON.stringify(evidence.locator)}</dd></div><div><dt>可用时点</dt><dd>{evidence.availableAt}</dd></div></dl><div className="ros-evidence-row__actions">{evidence.sourceTitle && <span>{evidence.sourceTitle}</span>}{evidence.sourceUrl ? <a className="ros-button ros-button--secondary" href={evidence.sourceUrl} target="_blank" rel="noopener noreferrer">打开冻结来源</a> : <span>冻结来源地址未记录</span>}</div></article>)}</section></section>}</CaseFrame>; }

export function CaseDocumentsPage() { return <CaseFrame>{(_data, caseId) => <CaseDocumentsContent caseId={caseId} />}</CaseFrame>; }
function CaseDocumentsContent({ caseId }: { caseId: string }) {
  const [documents, setDocuments] = useState<SourceDocumentView[] | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<{ document: SourceDocumentView; spans: DocumentSpan[] } | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setDocuments(null); setDetail(null); setError(null); researchClient.getDocuments({ caseId }).then((value) => { if (!active) return; setDocuments(value); setSelectedId(value[0]?.id ?? null); }).catch(() => active && setError("无法读取这个 Case 的原文资料；系统没有展示其他 Case 的替代内容。")); return () => { active = false; }; }, [caseId]);
  useEffect(() => { let active = true; if (!selectedId) return; setDetail(null); researchClient.getDocumentDetail(selectedId).then((value) => active && setDetail(value)).catch(() => active && setError("无法读取所选资料的冻结内容。")); return () => { active = false; }; }, [selectedId]);
  return <section className="ros-documents"><header className="ros-section-heading"><div><p className="ros-eyebrow">来源阅读</p><h2>原文资料</h2><p>只显示已关联当前 Case 的资料；正文、定位与版本来自资料记录，而非系统推测。</p></div><Link className="ros-button ros-button--secondary" to={`/events/${caseId}/evidence`}>返回命题与证据</Link></header>{error && <p className="ros-error">{error}</p>}{!documents ? <div className="ros-empty">正在读取当前 Case 的原文资料…</div> : documents.length === 0 ? <div className="ros-empty">当前 Case 暂无可读取的原文资料；这不表示其他 Case 的资料可以被复用。</div> : <div className="ros-documents-grid"><section className="ros-document-list" aria-label="当前 Case 原文资料">{documents.map((document) => <button type="button" key={document.id} className={`ros-document-row${document.id === selectedId ? " is-selected" : ""}`} onClick={() => setSelectedId(document.id)}><span className={`ros-pill ${document.parse_quality === "ok" ? "ros-pill--system" : "ros-pill--human"}`}>{document.parse_quality === "ok" ? "解析完成" : document.parse_quality === "partial" ? "解析不完整" : "解析失败"}</span><strong>{document.title || "未命名资料"}</strong><small>{document.publisher || "发布方未记录"} · {document.document_type || "类型未记录"}</small><small>{document.version_label || "版本未记录"} · {document.span_count} 个定位片段</small></button>)}</section><section className="ros-document-reader" aria-live="polite">{!detail ? <div className="ros-empty ros-empty--compact">正在读取冻结内容…</div> : <DocumentReader detail={detail} />}</section></div>}</section>;
}
function DocumentReader({ detail }: { detail: { document: SourceDocumentView; spans: DocumentSpan[] } }) { const { document, spans } = detail; return <><header><span className="ros-pill ros-pill--system">{document.version_label || "版本未记录"}</span><h3>{document.title || "未命名资料"}</h3><p>内容快照（当前 V1 未提供原件文件）</p></header><dl className="ros-definition"><div><dt>来源类型</dt><dd>{document.document_type || "未记录"}</dd></div><div><dt>发布方</dt><dd>{document.publisher || "未记录"}</dd></div><div><dt>发布日期</dt><dd>{document.publish_date || "未记录"}</dd></div><div><dt>可用 / 采集时点</dt><dd>{document.available_at} / {document.acquired_at}</dd></div><div><dt>解析版本</dt><dd>{document.parser_version} · {document.parse_quality}</dd></div><div><dt>许可 / 展示范围</dt><dd>当前资料记录未提供</dd></div></dl>{document.parse_quality === "failed" ? <p className="ros-rulebox">该资料在 {document.parse_failure_stage || "未记录阶段"} 解析失败；保留资料记录，暂不能把它写成证据。</p> : <section className="ros-source-spans"><p className="ros-eyebrow">可定位正文片段</p>{spans.length ? spans.map((span) => <article key={span.id}><code>{JSON.stringify(span.locator)}</code><blockquote>{span.verbatim_text}</blockquote><small>{span.cited_by.length ? `已被 ${span.cited_by.length} 条证据关系引用` : "尚未被证据关系引用"}</small></article>) : <div className="ros-empty ros-empty--compact">当前资料没有返回可定位正文片段。</div>}</section>}</> }

export function CaseConclusionPage() {
  return <CaseFrame>{(data, caseId) => <section className="ros-case-columns">
    <div><article className="ros-panel ros-panel--conclusion"><p className="ros-eyebrow">当前判断 · {data.conclusion.state === "published" ? "已人工发布" : data.conclusion.state === "ai_draft" ? "AI 草案，未发布" : "暂不下结论"}</p><h2>{data.conclusion.text}</h2><p className="ros-conclusion-text">{data.conclusion.state === "published" ? "该版本只基于已审核资料；新运行只会追加待审证据，不会自动重写结论。" : "尚未审核的候选、二手转述和无授权材料都不会自动进入当前判断。"}</p></article><FactorList data={data} /></div>
    <aside className="ros-case-rail"><section className="ros-action-card"><p className="ros-eyebrow">下一步</p><h2>{data.nextAction.label}</h2><p>{data.lifecycle.currentGap || "先完成当前人工判断，再决定是否创建新的结论或范围版本。"}</p><Link className="ros-button ros-button--primary" to={`/events/${caseId}/${data.nextAction.kind === "review_evidence" || data.nextAction.kind === "review_conclusion" ? "review" : "monitor"}`}>{data.nextAction.kind.includes("review") ? "进入审核" : "查看持续研究"}</Link></section><section className="ros-rail-section"><p className="ros-eyebrow">持续研究</p><h2>{data.lifecycle.activeRunId ? "系统正在受控补证" : "等待下一验证事件"}</h2><p>范围版本 v{data.scope.version} · 仅允许来源内的材料可进入后续审核。</p><Link to={`/events/${caseId}/monitor`}>查看运行记录 →</Link></section><section className="ros-rail-section"><p className="ros-eyebrow">结论依据</p><p>{data.conclusion.citations.length} 条可回溯引用；每条都保留原文定位、可用时点与审核状态。</p></section></aside>
  </section>}</CaseFrame>;
}

export function CaseReviewPage() { return <CaseFrame>{(_data, caseId) => <ReviewContent caseId={caseId} />}</CaseFrame>; }
function ReviewContent({ caseId }: { caseId: string }) {
  const [queue, setQueue] = useState<Awaited<ReturnType<EventResearchClient["getEventReviewQueue"]>> | null>(null);
  const [reload, setReload] = useState(0);
  useEffect(() => { researchClient.getEventReviewQueue(caseId).then(setQueue).catch(() => setQueue(null)); }, [caseId, reload]);
  if (!queue) return <div className="ros-empty ros-page-gap">正在读取待审核证据；不可访问的来源不会进入审核动作。</div>;
  const actionable = queue.items.filter((item) => item.canAccept);
  return <section className="ros-review-workbench"><header className="ros-section-heading"><div><p className="ros-eyebrow">人工审核</p><h2>{queue.summary.pending} 条待审核关系</h2></div><span className="ros-muted">候选仅供核对；不会自动采纳</span></header>{actionable.length === 0 ? <div className="ros-empty">当前没有待审核候选。</div> : actionable.map((item) => <ReviewItem item={item} onDecided={() => setReload((value) => value + 1)} key={item.proposalId} />)}{queue.summary.invalidSource > 0 && <p className="ros-rulebox">另有 {queue.summary.invalidSource} 条来源因许可或可验证性不足被排除，不能在此采纳为正式证据。</p>}</section>;
}

function ReviewItem({ item, onDecided }: { item: Awaited<ReturnType<EventResearchClient["getEventReviewQueue"]>>["items"][number]; onDecided: () => void }) {
  const [reason, setReason] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function decide(outcome: "confirmed" | "rejected" | "needs_more_evidence") { if (!reason.trim()) return; setSubmitting(true); setError(null); try { await researchClient.reviewProposal(item.proposalId, { outcome, reason: reason.trim(), reviewer_id: "human:researcher", expected_version: item.proposalVersion }); onDecided(); } catch { setError("提交审核决定失败；候选未被自动采纳。请刷新后重试。"); } finally { setSubmitting(false); } }
  return <article className="ros-review-item"><div><span className="ros-pill ros-pill--human">未经人工复核</span><h3>{item.thesisStatement || "未关联关键因素"}</h3><blockquote>{item.verbatimText || item.statementText || "未抽取到可定位原文"}</blockquote></div><dl><div><dt>原文定位</dt><dd>{JSON.stringify(item.locator)}</dd></div><div><dt>可用时点</dt><dd>{item.availableAt || "未记录"}</dd></div><div><dt>来源与许可</dt><dd>{item.sourceStatusReason}</dd></div></dl><div className="ros-review-actions"><span>{item.aiRole || "候选关系"} · {item.proposalReason}</span>{item.documentSourceUrl ? <a className="ros-button ros-button--secondary" href={item.documentSourceUrl} target="_blank" rel="noopener noreferrer">打开冻结来源</a> : <span>冻结来源地址未记录</span>}</div><div className="ros-review-decision"><label>审核理由<textarea aria-label="审核理由" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="说明为何原文支持或不支持这个关系" /></label><div><button className="ros-button ros-button--primary" type="button" disabled={!reason.trim() || submitting} onClick={() => decide("confirmed")}>确认采纳</button><button className="ros-button ros-button--secondary" type="button" disabled={!reason.trim() || submitting} onClick={() => decide("needs_more_evidence")}>要求补充证据</button><button className="ros-button ros-button--secondary" type="button" disabled={!reason.trim() || submitting} onClick={() => decide("rejected")}>驳回候选</button></div>{error && <p className="ros-error">{error}</p>}</div></article>;
}

export function CaseWikiPage() { return <CaseFrame>{(_data, caseId) => <WikiContent caseId={caseId} />}</CaseFrame>; }
function WikiContent({ caseId }: { caseId: string }) {
  const [graph, setGraph] = useState<Graph | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showCandidates, setShowCandidates] = useState(true);
  useEffect(() => { researchOsApi.graph(caseId).then((value) => { setGraph(value); setSelectedId(value.nodes[0]?.id ?? null); }).catch(() => setGraph(null)); }, [caseId]);
  if (!graph) return <div className="ros-empty ros-page-gap">Case Wiki 暂无可读取图谱。系统不会以示例节点替代真实证据。</div>;
  const candidateNode = (node: Graph["nodes"][number]) => node.kind === "proposal" || node.properties?.review_state === "machine_generated";
  const candidateEdge = (edge: Graph["edges"][number]) => edge.review_state === "machine_generated";
  const nodes = graph.nodes.filter((node) => showCandidates || !candidateNode(node));
  const visibleNodeIds = new Set(nodes.map((node) => node.id));
  const edges = graph.edges.filter((edge) => showCandidates || (!candidateEdge(edge) && visibleNodeIds.has(edge.source) && visibleNodeIds.has(edge.target)));
  const nodeById = new Map(graph.nodes.map((node) => [node.id, node]));
  const selected = nodes.find((node) => node.id === selectedId) || nodes[0];
  const selectedEdges = graph.edges.filter((edge) => edge.source === selected?.id || edge.target === selected?.id);
  const reviewed = graph.edges.filter((edge) => edge.review_state !== "machine_generated").length;
  const candidates = graph.edges.filter((edge) => edge.review_state === "machine_generated").length;
  return <section className="ros-wiki"><header className="ros-section-heading"><div><p className="ros-eyebrow">Case Wiki · 证据关系</p><h2>从资料到基金表达的可追溯路径</h2></div><button className="ros-button ros-button--secondary" type="button" onClick={() => setShowCandidates((value) => !value)}>{showCandidates ? `隐藏 AI 候选 ${candidates}` : `显示 AI 候选 ${candidates}`}</button></header><div className="ros-wiki-grid"><div className="ros-wiki-wrap"><div className="ros-wiki-bar"><span>已审核关系 {reviewed}</span><span>实线：已审核 · 虚线：未经人工复核</span></div><div className="ros-wiki-canvas" aria-label="Case Wiki 节点列表">{nodes.map((node) => <button type="button" onClick={() => setSelectedId(node.id)} className={`ros-wiki-node ros-wiki-node--${node.kind}${node.id === selected?.id ? " is-selected" : ""}${candidateNode(node) ? " is-candidate" : ""}`} key={node.id}><span>{node.kind}</span><strong>{node.label}</strong><small>{candidateNode(node) ? "AI 候选，未进入结论" : "已进入 Case 图谱"}</small></button>)}</div><div className="ros-wiki-edges" aria-label="Case Wiki 关系">{edges.map((edge) => <button className={`ros-wiki-edge${candidateEdge(edge) ? " is-candidate" : ""}`} type="button" onClick={() => setSelectedId(edge.target)} key={`${edge.source}-${edge.target}-${edge.semantic_kind}`}><span>{nodeById.get(edge.source)?.label || edge.source}</span><i aria-hidden="true">→</i><span>{nodeById.get(edge.target)?.label || edge.target}</span><b>{edge.semantic_kind}</b><small>{candidateEdge(edge) ? "AI 候选，未经复核" : "已审核关系"}</small></button>)}{edges.length === 0 && <p className="ros-empty ros-empty--compact">当前筛选下暂无可展示关系。</p>}</div></div><aside className="ros-wiki-inspector">{selected ? <><span className={`ros-pill ${candidateNode(selected) ? "ros-pill--human" : "ros-pill--system"}`}>{candidateNode(selected) ? "未经人工复核" : "已审核对象"}</span><h3>{selected.label}</h3><p>{selected.kind} · {selectedEdges.length} 条关联关系</p><dl>{Object.entries(selected.properties || {}).slice(0, 4).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><div className="ros-legend"><span>关系：{selectedEdges.map((edge) => edge.semantic_kind).join("、") || "暂无"}</span><span>AI 候选不继承结论、市场表达或基金暴露。</span></div></> : <p>选择一个节点以查看其证据与关系。</p>}</aside></div></section>;
}

export function CaseMarketPage() { return <CaseFrame>{(_data, caseId) => <MarketExpressionContent caseId={caseId} />}</CaseFrame>; }
function MarketContent({ caseId, data }: { caseId: string; data: EventWorkbench }) {
  const [exposure, setExposure] = useState<FundExposure | null>(null);
  useEffect(() => { researchOsApi.exposure(caseId).then(setExposure).catch(() => setExposure(null)); }, [caseId]);
  return <section className="ros-market"><header className="ros-section-heading"><div><p className="ros-eyebrow">市场与表达</p><h2>把研报判断落到可验证的市场表达</h2></div><span className="ros-pill ros-pill--system">仅展示已披露持仓</span></header><p className="ros-market-intro">先验证关键因素，再分别观察基本面、股票市场和基金披露暴露。它们相关，但不是同一种证据。</p><div className="ros-market-workbench"><section className="ros-market-factors"><p className="ros-eyebrow">关键因素验证</p>{data.factors.map((factor) => <article className="ros-market-factor" key={factor.position}><i className={factor.reviewedContradictionCount > 0 ? "is-risk" : factor.currentGap ? "is-gap" : ""} /><div><strong>{factor.statement}</strong><small>支持 {factor.reviewedSupportCount} · 反证 {factor.reviewedContradictionCount} · 待核对 {factor.pendingProposalCount}</small></div><span>{factor.reviewedContradictionCount > 0 ? "存在反证" : factor.currentGap ? "证据缺口" : "持续验证"}</span></article>)}</section><section className="ros-market-chain"><p className="ros-eyebrow">影响路径</p><div className="ros-chain-row"><article><span>研报主张</span><b>当前 Case 判断</b><small>只引用已审核证据</small></article><i>→</i><article><span>关键因素</span><b>可验证指标</b><small>支持 / 反证 / 缺口</small></article><i>→</i><article><span>公司 / 股票</span><b>基本面与市场观测</b><small>不自动归因</small></article><i>→</i><article><span>基金披露</span><b>报告期内暴露</b><small>非实时仓位</small></article></div><p className="ros-note">股票事件窗口是观测结果；只有时点、机制和反证都足够时，才可以形成有限且带条件的判断。</p></section><aside className="ros-market-rail"><p className="ros-eyebrow">基金披露暴露</p><h2>{exposure ? `截至 ${exposure.as_of}` : "暂无可用披露"}</h2>{!exposure ? <p>当前 Case 尚未绑定已审核公司关系，或没有可访问的基金披露数据。</p> : exposure.funds.map((fund) => <article className="ros-fund-row" key={fund.fund_id}><strong>{fund.fund_name} <small>{fund.fund_code}</small></strong><span>主题暴露 {(fund.theme_exposure * 100).toFixed(2)}%</span>{fund.positions.map((position) => <small key={position.stock_id}>{position.stock_name} · {(position.weight * 100).toFixed(2)}% · {position.report_period}</small>)}</article>)}<p className="ros-market-warning">披露暴露按报告期、披露日和采集日理解，不表示实时持仓，也不构成交易建议。</p></aside></div></section>;
}

type RunEvent = { seq: number; stage: string | null; status: string | null; message: string | null; details: Record<string, unknown>; createdAt?: string };
export function CaseMonitorPage() { return <CaseFrame>{(data, caseId) => <MonitorContent caseId={caseId} activeRunId={data.lifecycle.activeRunId} />}</CaseFrame>; }
function MonitorContent({ caseId, activeRunId }: { caseId: string; activeRunId: string | null }) {
  const [detail, setDetail] = useState<MonitorDetail | null>(null);
  const [events, setEvents] = useState<RunEvent[]>([]);
  const [drawer, setDrawer] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedRunId, setSelectedRunId] = useState<string | null>(activeRunId);
  const [starting, setStarting] = useState(false);
  useEffect(() => { researchOsApi.monitor(caseId).then((value) => { setDetail(value); setSelectedRunId((current) => current || value.latest_run?.id || null); }).catch(() => setError("监控配置尚不可用。")); }, [caseId]);
  useEffect(() => { if (!selectedRunId) { setEvents([]); return; } researchOsApi.runEvents(selectedRunId).then((response) => setEvents(response.items.map((event) => ({ seq: event.seq, stage: event.stage ?? null, status: event.status ?? null, message: event.message ?? null, details: event.details ?? {}, createdAt: event.created_at })))).catch(() => setError("该运行的事件记录暂不可读。")); }, [selectedRunId]);
  const run = selectedRunId && detail?.latest_run?.id === selectedRunId ? detail.latest_run : selectedRunId ? { id: selectedRunId, status: "queued", stage: "queued", updated_at: new Date().toISOString() } : null;
  async function startNow() { if (!detail?.monitor) { setError("请先保存一份 CaseMonitor 配置，系统才能冻结本次补证范围。"); return; } setStarting(true); setError(null); try { const created = await researchClient.startResearchRun(caseId, { max_rounds: 3, budget: detail.monitor.budget, auto_execute: false }); setSelectedRunId(created.id); setDrawer(true); } catch { setError("无法创建立即补证运行；没有写入部分运行。请检查服务状态后重试。"); } finally { setStarting(false); } }
  return <section className="ros-monitor"><header className="ros-section-heading"><div><p className="ros-eyebrow">监控与版本</p><h2>每一次运行均可检查、复现与配置</h2></div><div className="ros-header-actions"><button className="ros-button ros-button--primary" type="button" disabled={starting || !detail?.monitor} onClick={startNow}>{starting ? "正在创建运行…" : "立即补证一次"}</button><button className="ros-button ros-button--secondary" type="button" disabled={!selectedRunId} onClick={() => setDrawer(true)}>打开运行详情</button></div></header>{error && <p className="ros-error">{error}</p>}<div className="ros-monitor-grid"><section className="ros-card ros-run-card"><header className="ros-card-head"><div><p className="ros-eyebrow">{run ? "选中的运行" : "尚未开始运行"}</p><h2>{run ? `${run.stage} · ${run.status}` : "先配置持续研究"}</h2></div><span>{run ? `更新于 ${run.updated_at}` : ""}</span></header><div className="ros-run-summary"><strong>{events.length ? "系统的每一步都在记录" : "运行将从范围冻结开始记录"}</strong><p>{events.length ? "查看每个阶段的输入、允许来源、排除理由和输出；系统不会在后台悄悄改写结论。" : "立即运行或定时任务都会绑定有效的 CaseMonitor 配置版本。"}</p></div><ol className="ros-run-log">{events.length ? events.map((event) => <li key={event.seq}><span>{event.seq}</span><div><strong>{event.stage || "运行阶段"} · {event.status || "已记录"}</strong><p>{event.message || "无文字摘要"}</p><small>{Object.entries(event.details).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join("、") : String(value)}`).join(" · ")}</small></div></li>) : <li><span>1</span><div><strong>等待运行</strong><p>尚无结构化运行事件；新运行会从读取并冻结配置开始逐条记录。</p></div></li>}</ol></section><aside className="ros-monitor-config"><section className="ros-panel"><p className="ros-eyebrow">当前 CaseMonitor · {detail?.monitor ? `配置 v${detail.monitor.version}` : "未配置"}</p><h2>用于未来运行的配置</h2><p>它只决定下一次立即补证与定时任务；历史运行必须以它自己的冻结事件回放。</p>{detail?.monitor ? <dl className="ros-definition"><div><dt>运行频率</dt><dd>{detail.monitor.frequency}</dd></div><div><dt>允许来源</dt><dd>{detail.monitor.allowed_source_types.join("、")}</dd></div><div><dt>下一验证</dt><dd>{detail.monitor.next_verification_event}</dd></div><div><dt>单次上限</dt><dd>{detail.monitor.budget} 份候选资料</dd></div></dl> : <div className="ros-empty ros-empty--compact">尚未设置监控条件。</div>}<Link className="ros-button ros-button--primary" to={`/events/${caseId}/monitor/config`}>调整配置</Link></section><p className="ros-rulebox"><b>可复现要求：</b>触发人/原因、配置版本、查询口径、来源许可、资料版本、阶段输出、排除理由和失败原因均要可查看。</p></aside></div>{drawer && selectedRunId && <RunDrawer run={run} detail={detail} events={events} onClose={() => setDrawer(false)} />}</section>;
}

function RunDrawer({ run, detail, events, onClose }: { run: MonitorDetail["latest_run"] | { id: string; status: string; stage: string; updated_at: string } | null; detail: MonitorDetail | null; events: RunEvent[]; onClose: () => void }) { const scope = events.find((event) => event.stage === "scope")?.details; const value = (key: string) => scope?.[key]; const list = (key: string) => { const current = value(key); return Array.isArray(current) ? current.join("、") : current ? String(current) : null; }; return <aside className="ros-run-drawer" aria-label="运行详情"><header><div><p className="ros-eyebrow">ResearchRun · {run?.id || "尚无运行"}</p><h2>{run ? `${run.stage} · ${run.status}` : "运行详情"}</h2><p>{scope ? "以下口径来自本次运行的冻结事件。" : "冻结口径尚未在事件记录中提供，不能用当前配置替代。"}</p></div><button aria-label="关闭运行详情" type="button" onClick={onClose}>×</button></header><div className="ros-drawer-body"><section className="ros-run-scope"><p className="ros-eyebrow">本次运行口径</p><dl><div><dt>触发方式</dt><dd>{list("trigger") || "未记录"}</dd></div><div><dt>配置版本</dt><dd>{list("monitor_version_id") || "未记录"}</dd></div><div><dt>范围因素</dt><dd>{list("factor_ids") || "未记录"}</dd></div><div><dt>允许来源</dt><dd>{list("allowed_source_types") || "未记录"}</dd></div><div><dt>检索预算</dt><dd>{list("budget") || "未记录"}</dd></div><div><dt>运行事件</dt><dd>{events.length} 条</dd></div></dl>{!scope && detail?.monitor && <p className="ros-note">当前配置为 v{detail.monitor.version}，仅供下一次运行使用。</p>}</section><ol className="ros-run-log">{events.map((event) => <li key={event.seq}><span>{event.seq}</span><div><strong>{event.stage || "阶段"}</strong><p>{event.message || "无文字摘要"}</p></div></li>)}</ol></div></aside>; }

export function MonitorConfigPage() { return <CaseFrame>{(_data, caseId) => <MonitorConfigForm caseId={caseId} />}</CaseFrame>; }
function MonitorConfigForm({ caseId }: { caseId: string }) {
  const [detail, setDetail] = useState<MonitorDetail | null>(null); const [selected, setSelected] = useState<string[]>([]); const [frequency, setFrequency] = useState("weekday_08_30"); const [sources, setSources] = useState<string[]>(["licensed_provider"]); const [nextEvent, setNextEvent] = useState(""); const [budget, setBudget] = useState(20); const [reason, setReason] = useState("调整监控范围"); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { researchOsApi.monitor(caseId).then((value) => { setDetail(value); setSelected(value.monitor?.factor_ids ?? value.confirmed_factors.map((factor) => factor.id)); setFrequency(value.monitor?.frequency ?? "weekday_08_30"); setSources(value.monitor?.allowed_source_types ?? ["licensed_provider"]); setNextEvent(value.monitor?.next_verification_event ?? ""); setBudget(value.monitor?.budget ?? 20); }).catch(() => setMessage("无法读取当前可确认因素。")); }, [caseId]);
  const toggleFactor = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); const toggleSource = (source: string) => setSources((current) => current.includes(source) ? current.filter((value) => value !== source) : [...current, source]);
  async function save() { if (!selected.length || !sources.length || !nextEvent.trim() || !reason.trim()) { setMessage("请选择至少一个已确认因素、一个允许来源，并说明下一验证事件与变更原因。"); return; } try { const saved = await researchOsApi.saveMonitor(caseId, { actor: "human:researcher", frequency, factor_ids: selected, allowed_source_types: sources as ("licensed_provider" | "company_disclosure" | "uploaded_file" | "pasted_snapshot")[], next_verification_event: nextEvent, budget, change_reason: reason }); setMessage(`已保存监控版本 v${saved.version}；此前版本保持不变。`); } catch { setMessage("保存失败，未写入任何配置版本。"); } }
  return <section className="ros-panel ros-config"><p className="ros-eyebrow">配置监控</p><h2>调整后会创建新的可复现版本</h2><p>系统只使用这里明确允许的来源和已确认因素；立即补证与定时运行都引用同一版本。</p>{!detail ? <div className="ros-empty ros-empty--compact">正在读取可配置因素…</div> : <div className="ros-config-form"><fieldset><legend>已确认关键因素</legend>{detail.confirmed_factors.map((factor) => <label key={factor.id}><input type="checkbox" checked={selected.includes(factor.id)} onChange={() => toggleFactor(factor.id)} />{factor.statement}</label>)}</fieldset><label>频率<select value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="weekday_08_30">工作日 08:30</option><option value="weekday_12_30">工作日 12:30</option><option value="daily_20_00">每日 20:00</option></select></label><fieldset><legend>允许来源</legend>{[["licensed_provider", "授权数据源"], ["company_disclosure", "公司披露"], ["uploaded_file", "人工上传"], ["pasted_snapshot", "粘贴快照"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={sources.includes(value)} onChange={() => toggleSource(value)} />{label}</label>)}</fieldset><label>下一验证事件<input value={nextEvent} onChange={(event) => setNextEvent(event.target.value)} placeholder="例如：2026Q1 财报披露" /></label><label>检索预算<input type="number" min="1" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><label>变更原因<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="ros-button ros-button--primary" type="button" onClick={save}>保存为新监控版本</button></div>}{message && <p className={message.startsWith("已保存") ? "ros-success" : "ros-error"}>{message}</p>}<Link className="ros-button ros-button--secondary" to={`/events/${caseId}/monitor`}>返回运行记录</Link></section>;
}
