import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, useParams } from "react-router-dom";

import { researchOsApi, type FundExposure, type Graph, type MonitorDetail } from "../../app/researchOsApi";
import { researchClient } from "../../data/researchClient";
import type { EventResearchClient, EventWorkbench } from "../../domain/eventResearch";

const tabs = [
  ["", "研究结论"], ["review", "证据审核"], ["wiki", "Case Wiki"], ["market", "市场与表达"], ["monitor", "监测与运行"],
];

function CaseFrame({ children }: { children: (workbench: EventWorkbench, caseId: string) => ReactNode }) {
  const { caseId = "" } = useParams();
  const [data, setData] = useState<EventWorkbench | null>(null);
  useEffect(() => { if (caseId) researchClient.getEventWorkbench(caseId).then(setData).catch(() => setData(null)); }, [caseId]);
  if (!data) return <main className="ros-page"><div className="ros-empty">正在读取 Case；若无权限或 Case 不存在，系统不会展示替代数据。</div></main>;
  return <main className="ros-page ros-case-page"><header className="ros-case-header"><p className="ros-eyebrow">Case · {data.event.ticker || "未绑定股票"}</p><h1>{data.event.eventTitle}</h1><p>{data.lifecycle.summary}</p><div className="ros-case-header__facts"><span>范围版本 v{data.scope.version}</span><span>已审核证据 {data.progress.verified}</span><span>待审核 {data.progress.pending}</span><span>当前运行 {data.lifecycle.activeRunId ? "可查看" : "无"}</span></div></header><nav className="ros-case-tabs" aria-label="Case 页面">{tabs.map(([suffix, label]) => <NavLink key={suffix} end={suffix === ""} to={`/events/${caseId}${suffix ? `/${suffix}` : ""}`}>{label}</NavLink>)}</nav>{children(data, caseId)}</main>;
}

export function CaseConclusionPage() { return <CaseFrame>{(data) => <section className="ros-case-columns"><article className="ros-panel ros-panel--conclusion"><p className="ros-eyebrow">当前结论</p><h2>{data.conclusion.state === "published" ? "已发布研究结论" : "尚未形成可发布结论"}</h2><p className="ros-conclusion-text">{data.conclusion.text}</p><p className="ros-note">{data.conclusion.state === "published" ? "结论基于已审核证据；后续运行只能追加新证据，不会重写本记录。" : "AI 草案、候选关系与未审核材料不会自动进入结论。"}</p></article><section className="ros-panel"><p className="ros-eyebrow">关键因素</p>{data.factors.map((factor) => <div className="ros-factor-row" key={factor.position}><span>{String(factor.position).padStart(2, "0")}</span><div><strong>{factor.statement}</strong><small>支持 {factor.reviewedSupportCount} · 反证 {factor.reviewedContradictionCount} · 待审核 {factor.pendingProposalCount}</small>{factor.currentGap && <em>{factor.currentGap}</em>}</div></div>)}</section></section>}</CaseFrame>; }

export function CaseReviewPage() { return <CaseFrame>{(_data, caseId) => <ReviewContent caseId={caseId} />}</CaseFrame>; }
function ReviewContent({ caseId }: { caseId: string }) { const [queue, setQueue] = useState<Awaited<ReturnType<EventResearchClient["getEventReviewQueue"]>> | null>(null); useEffect(() => { researchClient.getEventReviewQueue(caseId).then(setQueue).catch(() => setQueue(null)); }, [caseId]); if (!queue) return <div className="ros-empty">正在读取待审核证据；不可访问的来源不会进入审核动作。</div>; return <section className="ros-review-list"><div className="ros-section-heading"><div><p className="ros-eyebrow">人工审核</p><h2>{queue.summary.pending} 条待审核关系</h2></div><span className="ros-muted">AI 候选仅作为待核对材料</span></div>{queue.items.map((item) => <article className="ros-review-item" key={item.proposalId}><span className="ros-pill ros-pill--human">未经人工复核</span><h3>{item.thesisStatement || "未关联因素"}</h3><blockquote>{item.verbatimText || item.statementText || "未抽取到可定位原文"}</blockquote><dl><div><dt>原文定位</dt><dd>{JSON.stringify(item.locator)}</dd></div><div><dt>可用时间</dt><dd>{item.availableAt || "未记录"}</dd></div><div><dt>来源状态</dt><dd>{item.sourceStatusReason}</dd></div></dl></article>)}</section>; }

export function CaseWikiPage() { return <CaseFrame>{(_data, caseId) => <WikiContent caseId={caseId} />}</CaseFrame>; }
function WikiContent({ caseId }: { caseId: string }) { const [graph, setGraph] = useState<Graph | null>(null); useEffect(() => { researchOsApi.graph(caseId).then(setGraph).catch(() => setGraph(null)); }, [caseId]); if (!graph) return <div className="ros-empty">Case Wiki 暂无可读取图谱。系统不会以示例节点替代真实证据。</div>; const candidates = graph.edges.filter((edge) => edge.review_state === "machine_generated"); const reviewed = graph.edges.filter((edge) => edge.review_state !== "machine_generated"); return <section className="ros-wiki"><div className="ros-section-heading"><div><p className="ros-eyebrow">Case Wiki</p><h2>证据关系与研究对象</h2></div><span className="ros-muted">已审核 {reviewed.length} · AI 候选 {candidates.length}</span></div><div className="ros-wiki-grid"><div className="ros-wiki-canvas">{graph.nodes.map((node) => <article className={`ros-wiki-node ros-wiki-node--${node.kind}`} key={node.id}><span>{node.kind}</span><strong>{node.label}</strong><small>{node.properties?.review_state === "machine_generated" ? "AI 候选" : "已进入 Case 图谱"}</small></article>)}</div><aside className="ros-wiki-inspector"><p className="ros-eyebrow">图谱说明</p><h3>关系状态严格分层</h3><p>实线代表已审核关系；虚线候选不继承结论、市场表达或基金暴露。</p><div className="ros-legend"><span>— 已审核</span><span>┄ AI 候选</span></div></aside></div></section>; }

export function CaseMarketPage() { return <CaseFrame>{(_data, caseId) => <MarketContent caseId={caseId} />}</CaseFrame>; }
function MarketContent({ caseId }: { caseId: string }) { const [exposure, setExposure] = useState<FundExposure | null>(null); useEffect(() => { researchOsApi.exposure(caseId).then(setExposure).catch(() => setExposure(null)); }, [caseId]); return <section className="ros-market"><div className="ros-section-heading"><div><p className="ros-eyebrow">市场与表达</p><h2>从关键因素到股票与基金披露</h2></div><span className="ros-pill ros-pill--system">仅展示已披露持仓</span></div><div className="ros-market-path"><span>研报主张</span><b>→</b><span>关键因素验证</span><b>→</b><span>公司 / 股票</span><b>→</b><span>基金披露暴露</span></div><div className="ros-market-grid"><article className="ros-panel"><h3>基本面与市场观测</h3><p>这里将只呈现已审核的关键因素、指标验证和事件窗口观测；不会把同期波动自动归因为事件。</p><div className="ros-empty ros-empty--compact">当前 Case 尚无独立的研报主张验证记录。</div></article><article className="ros-panel"><h3>基金披露暴露</h3>{!exposure ? <div className="ros-empty ros-empty--compact">没有可用的基金披露数据，或当前 Case 尚未绑定已审核公司关系。</div> : exposure.funds.map((fund) => <div className="ros-fund-row" key={fund.fund_id}><strong>{fund.fund_name} <small>{fund.fund_code}</small></strong><span>主题暴露 {(fund.theme_exposure * 100).toFixed(2)}%</span>{fund.positions.map((position) => <small key={position.stock_id}>{position.stock_name} · 权重 {(position.weight * 100).toFixed(2)}% · 报告期 {position.report_period}</small>)}</div>)}</article></div><p className="ros-note">基金仓位按披露报告期呈现，不代表实时持仓；市场表现是观测，不构成自动因果或交易建议。</p></section>; }

export function CaseMonitorPage() { return <CaseFrame>{(data, caseId) => <MonitorContent caseId={caseId} activeRunId={data.lifecycle.activeRunId} />}</CaseFrame>; }
function MonitorContent({ caseId, activeRunId }: { caseId: string; activeRunId: string | null }) { const [detail, setDetail] = useState<MonitorDetail | null>(null); const [events, setEvents] = useState<{ seq: number; stage: string | null; status: string | null; message: string | null; details: Record<string, unknown> }[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { researchOsApi.monitor(caseId).then(setDetail).catch(() => setError("监控配置尚不可用。")); if (activeRunId) researchOsApi.runEvents(activeRunId).then((response) => setEvents(response.items.map((event) => ({ seq: event.seq, stage: event.stage ?? null, status: event.status ?? null, message: event.message ?? null, details: event.details ?? {} })))).catch(() => undefined); }, [caseId, activeRunId]); return <section className="ros-monitor"><div className="ros-section-heading"><div><p className="ros-eyebrow">监测与运行</p><h2>每一次运行均可检查、复现与配置</h2></div><span className="ros-muted">运行记录不会被后台状态覆盖</span></div>{error && <p className="ros-error">{error}</p>}<div className="ros-monitor-grid"><article className="ros-panel"><h3>有效监控版本</h3>{detail?.monitor ? <dl className="ros-definition"><div><dt>版本</dt><dd>v{detail.monitor.version} · {detail.monitor.frequency}</dd></div><div><dt>允许来源</dt><dd>{detail.monitor.allowed_source_types.join("、")}</dd></div><div><dt>下一验证事件</dt><dd>{detail.monitor.next_verification_event}</dd></div><div><dt>变更原因</dt><dd>{detail.monitor.change_reason}</dd></div><div><dt>操作者 / 时间</dt><dd>{detail.monitor.changed_by} · {detail.monitor.created_at}</dd></div></dl> : <div className="ros-empty ros-empty--compact">尚未配置定时监控。保存后会产生版本 v1，修改会形成新版本。</div>}<Link className="ros-button ros-button--secondary" to={`/events/${caseId}/monitor/config`}>调整监控配置</Link></article><article className="ros-panel"><h3>本次运行明细</h3>{events.length === 0 ? <div className="ros-empty ros-empty--compact">暂无结构化运行事件。新的运行会从范围冻结开始逐条记录。</div> : <ol className="ros-run-log">{events.map((event) => <li key={event.seq}><span>{String(event.seq).padStart(2, "0")}</span><div><strong>{event.stage} · {event.status}</strong><p>{event.message}</p><small>{Object.entries(event.details).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join("、") : String(value)}`).join(" · ")}</small></div></li>)}</ol>}</article></div></section>; }

export function MonitorConfigPage() { return <CaseFrame>{(_data, caseId) => <MonitorConfigForm caseId={caseId} />}</CaseFrame>; }
function MonitorConfigForm({ caseId }: { caseId: string }) {
  const [detail, setDetail] = useState<MonitorDetail | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const [frequency, setFrequency] = useState("weekday_08_30");
  const [sources, setSources] = useState<string[]>(["licensed_provider"]);
  const [nextEvent, setNextEvent] = useState("");
  const [budget, setBudget] = useState(20);
  const [reason, setReason] = useState("调整监控范围");
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { researchOsApi.monitor(caseId).then((value) => { setDetail(value); setSelected(value.monitor?.factor_ids ?? value.confirmed_factors.map((factor) => factor.id)); setFrequency(value.monitor?.frequency ?? "weekday_08_30"); setSources(value.monitor?.allowed_source_types ?? ["licensed_provider"]); setNextEvent(value.monitor?.next_verification_event ?? ""); setBudget(value.monitor?.budget ?? 20); }).catch(() => setMessage("无法读取当前可确认因素。")); }, [caseId]);
  function toggleFactor(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }
  function toggleSource(source: string) { setSources((current) => current.includes(source) ? current.filter((value) => value !== source) : [...current, source]); }
  async function save() { if (selected.length === 0 || sources.length === 0 || !nextEvent.trim() || !reason.trim()) { setMessage("请选择至少一个已确认因素、一个允许来源，并说明下一验证事件与变更原因。"); return; } try { const saved = await researchOsApi.saveMonitor(caseId, { actor: "human:researcher", frequency, factor_ids: selected, allowed_source_types: sources as ("licensed_provider" | "company_disclosure" | "uploaded_file" | "pasted_snapshot")[], next_verification_event: nextEvent, budget, change_reason: reason }); setMessage(`已保存监控版本 v${saved.version}；此前版本保持不变。`); } catch { setMessage("保存失败，未写入任何配置版本。"); } }
  return <section className="ros-panel ros-config"><p className="ros-eyebrow">配置监控</p><h2>调整后会创建新的可复现版本</h2><p>系统会只使用这里明确允许的来源和已确认因素；即时运行与定时运行都引用同一版本。</p>{!detail ? <div className="ros-empty ros-empty--compact">正在读取可配置因素…</div> : <div className="ros-config-form"><fieldset><legend>已确认关键因素</legend>{detail.confirmed_factors.map((factor) => <label key={factor.id}><input type="checkbox" checked={selected.includes(factor.id)} onChange={() => toggleFactor(factor.id)} />{factor.statement}</label>)}</fieldset><label>频率<select value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="weekday_08_30">工作日 08:30</option><option value="weekday_12_30">工作日 12:30</option><option value="daily_20_00">每日 20:00</option></select></label><fieldset><legend>允许来源</legend>{[["licensed_provider", "授权数据源"], ["company_disclosure", "公司披露"], ["uploaded_file", "人工上传"], ["pasted_snapshot", "粘贴快照"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={sources.includes(value)} onChange={() => toggleSource(value)} />{label}</label>)}</fieldset><label>下一验证事件<input value={nextEvent} onChange={(event) => setNextEvent(event.target.value)} placeholder="例如：2026Q1 财报披露" /></label><label>检索预算<input type="number" min="1" value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><label>变更原因<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="ros-button ros-button--primary" type="button" onClick={save}>保存为新监控版本</button></div>}{message && <p className={message.startsWith("已保存") ? "ros-success" : "ros-error"}>{message}</p>}<Link className="ros-button ros-button--secondary" to={`/events/${caseId}/monitor`}>返回运行记录</Link></section>; }
