"""Private continuous company study dossiers and durable dispatch.

Revision ID: 0076
Revises: 0075
All table and guard definitions are frozen in this migration.
"""

import sqlalchemy as sa
from alembic import op

revision = "0076"
down_revision = "0075"
branch_labels = None
depends_on = None


def company_guard_sql(dialect):
    tables = (
        "company_studies",
        "company_study_activities",
        "company_study_revisions",
        "company_study_monitors",
        "company_study_requests",
    )
    frozen = {
        "company_studies": (
            "id",
            "tenant_id",
            "subject_id",
            "name",
            "symbol",
            "market",
            "focus",
            "created_at",
        ),
        "company_study_activities": (
            "id",
            "study_id",
            "kind",
            "title",
            "text",
            "context_revision",
            "schedule_key",
            "created_at",
        ),
    }
    keys = {
        "company_studies": [("id",)],
        "company_study_activities": [("id",), ("study_id", "schedule_key")],
        "company_study_revisions": [("id",), ("study_id", "version")],
        "company_study_monitors": [("id",), ("study_id", "version")],
        "company_study_requests": [
            ("id",),
            ("tenant_id", "subject_id", "scope", "key_sha256"),
        ],
    }
    result = {table: [] for table in tables}
    for table in tables:
        for operation in ("DELETE",) if table in frozen else ("UPDATE", "DELETE"):
            name = f"cs_no_{operation.lower()}_{table}"
            if dialect == "sqlite":
                result[table].append(
                    f"CREATE TRIGGER {name} BEFORE {operation} ON {table} BEGIN SELECT RAISE(ABORT, 'company study history is immutable'); END"
                )
            else:
                result[table] += [
                    f"CREATE FUNCTION {name}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'company study history is immutable'; END; $$",
                    f"CREATE TRIGGER {name} BEFORE {operation} ON {table} FOR EACH ROW EXECUTE FUNCTION {name}()",
                ]
        if table in frozen:
            condition = " OR ".join(
                f"OLD.{col} IS NOT NEW.{col}"
                if dialect == "sqlite"
                else f"OLD.{col} IS DISTINCT FROM NEW.{col}"
                for col in frozen[table]
            )
            if table == "company_study_activities":
                comparison = "IS NOT" if dialect == "sqlite" else "IS DISTINCT FROM"
                condition += f" OR (OLD.prompt IS NOT NULL AND OLD.prompt {comparison} NEW.prompt) OR (OLD.run_spec_id IS NOT NULL AND OLD.run_spec_id {comparison} NEW.run_spec_id) OR (OLD.conversation_id IS NOT NULL AND OLD.conversation_id {comparison} NEW.conversation_id)"
            name = f"cs_frozen_{table}"
            if dialect == "sqlite":
                result[table].append(
                    f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} WHEN {condition} BEGIN SELECT RAISE(ABORT, 'company study definition is immutable'); END"
                )
            else:
                result[table] += [
                    f"CREATE FUNCTION {name}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF {condition} THEN RAISE EXCEPTION 'company study definition is immutable'; END IF; RETURN NEW; END; $$",
                    f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION {name}()",
                ]
        if dialect == "sqlite":
            conflicts = " OR ".join(
                "(" + " AND ".join(f"{col}=NEW.{col}" for col in columns) + ")"
                for columns in keys[table]
            )
            result[table].append(
                f"CREATE TRIGGER cs_no_replace_{table} BEFORE INSERT ON {table} WHEN EXISTS (SELECT 1 FROM {table} WHERE {conflicts}) BEGIN SELECT RAISE(ABORT, 'company study history is immutable'); END"
            )
    return result


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_studies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=True),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("focus", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("monitor_version", sa.Integer(), nullable=False),
        sa.Column("monitor_next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "market IN ('CN', 'HK', 'US', 'other')", name="ck_company_study_market"
        ),
        sa.CheckConstraint(
            "revision >= 0 AND monitor_version >= 0", name="ck_company_study_versions"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_study_owner",
        "company_studies",
        ["tenant_id", "subject_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "company_study_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("context_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("run_spec_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("schedule_key", sa.String(length=128), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('baseline', 'event', 'material', 'refresh', 'linked')",
            name="ck_company_activity_kind",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'starting', 'running', 'completed', 'failed', 'blocked')",
            name="ck_company_activity_status",
        ),
        sa.CheckConstraint("attempt >= 0", name="ck_company_activity_attempt"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["research_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_spec_id"],
            ["research_run_specs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["company_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "study_id", name="uq_company_activity_scope"),
        sa.UniqueConstraint(
            "study_id", "schedule_key", name="uq_company_activity_window"
        ),
    )
    op.create_index(
        "ix_company_activity_claim",
        "company_study_activities",
        ["status", "lease_expires_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_study_activities_study_id"),
        "company_study_activities",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "company_study_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("run_spec_id", sa.Uuid(), nullable=False),
        sa.Column("team_revision", sa.Integer(), nullable=False),
        sa.Column("output_ids", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "version >= 1 AND team_revision >= 1", name="ck_company_revision_versions"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id", "study_id"],
            ["company_study_activities.id", "company_study_activities.study_id"],
            name="fk_company_revision_activity",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["research_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_spec_id"],
            ["research_run_specs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["company_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "version", name="uq_company_study_revision"),
    )
    op.create_index(
        op.f("ix_company_study_revisions_study_id"),
        "company_study_revisions",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "company_study_monitors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("frequency", sa.String(length=16), nullable=False),
        sa.Column("focus", sa.Text(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "frequency IN ('daily', 'weekly')", name="ck_company_monitor_frequency"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused')", name="ck_company_monitor_status"
        ),
        sa.CheckConstraint("version >= 1", name="ck_company_monitor_version"),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["company_studies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "version", name="uq_company_monitor_version"),
    )
    op.create_index(
        op.f("ix_company_study_monitors_study_id"),
        "company_study_monitors",
        ["study_id"],
        unique=False,
    )
    op.create_table(
        "company_study_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("key_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "subject_id", "scope", "key_sha256", name="uq_company_request"
        ),
    )
    # ### end Alembic commands ###
    for statements in company_guard_sql(op.get_bind().dialect.name).values():
        for statement in statements:
            op.execute(statement)


def downgrade():
    dialect = op.get_bind().dialect.name
    guards = company_guard_sql(dialect)
    for table in reversed(tuple(guards)):
        op.drop_table(table)
    if dialect == "postgresql":
        for statements in guards.values():
            for statement in statements:
                if statement.startswith("CREATE FUNCTION"):
                    name = statement.split("FUNCTION ", 1)[1].split("(", 1)[0]
                    op.execute(f"DROP FUNCTION {name}()")
