import { expect, test } from '@playwright/test';
test('frozen source is readable from the Case with its locator', async ({ page, request }) => {
  const items = (await (await request.get('/api/v1/event-research')).json()).items;
  const item = items.find((entry: { event_title: string }) => entry.event_title === '证据审核浏览器验收');
  expect(item).toBeTruthy();
  const documents = (await (await request.get(`/api/v1/event-research/${item.case_id}/documents?limit=20`)).json()).items;
  const index = documents.findIndex((doc: { source_url: string | null }) => doc.source_url?.includes('extraction-fixture'));
  expect(index).toBeGreaterThanOrEqual(0);
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByRole('button', { name: '查看原始资料', exact: true }).click();
  await page.getByRole('button', { name: '查看冻结原文', exact: true }).nth(index).click();
  const detail = page.getByRole('article', { name: '冻结资料详情' });
  await expect(detail).toBeFocused();
  await expect(detail).toContainText('隔离验收原文：订单数量增加百分之十，后续收入仍需验证。');
  await page.setViewportSize({ width: 390, height: 844 });
  await detail.getByText('原文定位', { exact: true }).click();
  await expect(detail.locator('pre')).toContainText('paragraph');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await detail.scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/frozen-document-mobile.png' });
  const originalStatements = documents[index].statement_count;
  await page.getByLabel('我已核对来源，确认调用模型提取待审核候选').check();
  const extraction = page.waitForResponse((response) => response.url().includes(`/documents/${documents[index].id}/extract`) && response.request().method() === 'POST');
  await page.getByRole('button', { name: '从冻结资料提取候选' }).click();
  const extracted = await extraction;
  expect(extracted.status()).toBe(201);
  const result = await extracted.json();
  expect(result.candidate_count).toBeGreaterThan(0);
  expect(result.candidates.every((candidate: { review_state: string }) => candidate.review_state === 'awaiting_review')).toBeTruthy();
  await expect(page.getByText(/已生成 .* 条待审核候选，尚未发布正式陈述。/)).toBeVisible();
  const refreshed = await (await request.get(`/api/v1/event-research/${item.case_id}/documents/${documents[index].id}`)).json();
  expect(refreshed.document.statement_count).toBe(originalStatements);
  expect(refreshed.document.extraction_state).toBe('extracted_empty');
  await page.reload();
  await page.getByRole('button', { name: '查看原始资料', exact: true }).click();
  await page.getByRole('button', { name: '查看冻结原文', exact: true }).nth(index).click();
  await expect(page.getByRole('button', { name: '从冻结资料提取候选' })).toBeDisabled();
  await page.getByLabel('操作人', { exact: true }).fill('human:document-review');
  await page.getByRole('button', { name: '查看原子候选审核' }).click();
  const candidateRow = page.getByRole('article', { name: result.candidates[0].normalized_text, exact: true });
  await expect(candidateRow).toContainText(result.candidates[0].quote);
  await candidateRow.getByLabel('候选审核决定').selectOption('modified');
  await candidateRow.getByLabel('修订后的陈述').fill('人工核验：材料报告订单增加，收入变化仍待验证。');
  await candidateRow.getByLabel('候选审核理由').fill('已逐字核对冻结原文，保留收入不确定性。');
  await candidateRow.getByRole('button', { name: '保存候选审核' }).click();
  await expect(candidateRow).toContainText('审核已保存：修订后确认');
  const published = await (await request.get(`/api/v1/event-research/${item.case_id}/documents/${documents[index].id}`)).json();
  expect(published.document.statement_count).toBe(originalStatements + 1);
  await page.reload();
  await page.getByRole('button', { name: '查看原子候选审核' }).click();
  await expect(candidateRow).toContainText('正式陈述：人工核验：材料报告订单增加，收入变化仍待验证。');
  await expect(candidateRow.getByRole('button', { name: '保存候选审核' })).toHaveCount(0);
  await candidateRow.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/atomic-review-mobile.png' });


});
