import { expect, test } from '@playwright/test';
test('market workspace registers a source-bound reviewed claim and reloads it', async ({ page, request }) => {
  const cases = (await (await request.get('/api/v1/event-research')).json()).items;
  const item = cases.find((entry: { event_title: string }) => entry.event_title === '证据审核浏览器验收');
  let candidate: { id: string } | undefined;
  await expect.poll(async () => {
    const queue = await (await request.get(`/api/v1/research-cases/${item.case_id}/atomic-claims`)).json();
    candidate = queue.items.find((entry: { document_source_url: string }) => entry.document_source_url === 'event://pasted-news');
    return Boolean(candidate);
  }).toBe(true);
  const review = await request.post(`/api/v1/atomic-claims/${candidate!.id}/reviews`, { data: { outcome: 'confirmed', reviewer: 'human:fixture', reason: '准备市场登记来源', idempotency_key: 'market-source-fixture' } });
  expect(review.status()).toBe(201);
  const sourceId = (await review.json()).published_source_statement.id;
  const browserApiHeaders: Record<string, string>[] = [];
  page.on('request', (req) => { if (req.url().includes('/api/v1/')) browserApiHeaders.push(req.headers()); });
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByRole('link', { name: '打开市场研究与验证' }).click();
  await expect(page.getByRole('heading', { name: '市场研究与验证', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '进入市场研究' })).toBeDisabled();
  await page.getByLabel('市场研究操作人').fill('human:market-browser');
  await page.getByRole('button', { name: '进入市场研究' }).click();
  await page.getByRole('button', { name: '选择冻结原文并登记主张' }).click();
  await page.getByLabel('冻结原文陈述', { exact: true }).selectOption(sourceId);
  await page.getByLabel('主张表述', { exact: true }).fill('订单变化需要后续资料交叉验证。');
  await page.getByLabel('主张归属', { exact: true }).fill('隔离研究员');
  await expect(page.getByLabel('主张审核人')).toHaveValue('human:market-browser');
  await page.getByLabel('主张审核理由', { exact: true }).fill('已经核对冻结原文，登记为研究意见。');
  await page.getByRole('button', { name: '登记已审核主张', exact: true }).click();
  await expect(page.getByText(/已登记已审核主张；/)).toBeVisible();
  const expression = await (await request.get(`/api/v1/research-cases/${item.case_id}/market-expression`)).json();
  expect(expression.claims.some((claim: { text: string; reviewed_by: string }) => claim.text === '订单变化需要后续资料交叉验证。' && claim.reviewed_by === 'human:market-browser')).toBe(true);
  await page.reload();
  await page.getByLabel('市场研究操作人').fill('human:market-browser');
  await page.getByRole('button', { name: '进入市场研究' }).click();
  await expect(page.getByText('订单变化需要后续资料交叉验证。').first()).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/event-market-mobile.png' });
  expect(browserApiHeaders.length).toBeGreaterThan(0);
  expect(browserApiHeaders.every((headers) => !headers.authorization)).toBe(true);
});
