import { expect, test } from '@playwright/test';

test('a human reviews a frozen source and publishes the evidence through real HTTP', async ({ page, request }) => {
  const list = await request.get('/api/v1/event-research');
  const item = (await list.json()).items.find((entry: { event_title: string }) => entry.event_title === '证据审核浏览器验收');
  expect(item).toBeTruthy();
  const endpoint = `/api/v1/event-research/${item.case_id}/review-queue`;
  const before = await request.get(endpoint);
  const candidate = (await before.json()).items[0];
  expect(candidate.can_accept).toBe(true);
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByLabel('操作人', { exact: true }).fill('证据审核验收员');
  await page.getByRole('button', { name: '查看待审核证据', exact: true }).click();
  await expect(page.getByText('隔离验收原文：订单数量增加百分之十，后续收入仍需验证。', { exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: '审核结论', exact: true }).selectOption('confirmed');
  await page.getByLabel('审核理由', { exact: true }).fill('已核对冻结原文、来源与因素关系，同意采纳本条证据。');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole('article', { name: '隔离证据审核来源', exact: true }).screenshot({ path: 'test-results/evidence-review.png' });
  const decision = page.waitForResponse(r => r.url().endsWith(`/review-proposals/${candidate.proposal_id}/decisions`) && r.request().method() === 'POST');
  await page.getByRole('button', { name: '提交审核决定', exact: true }).click();
  const response = await decision;
  expect(response.status()).toBe(201);
  expect((await response.json()).published_entity_id).toBeTruthy();
  const after = await request.get(endpoint);
  expect((await after.json()).items).toHaveLength(0);
  await page.reload();
  await page.getByRole('button', { name: '查看待审核证据', exact: true }).click();
  await expect(page.getByRole('combobox', { name: '审核结论', exact: true })).toHaveCount(0);
  const workbench = await request.get(`/api/v1/event-research/${item.case_id}/workbench`);
  const body = await workbench.json();
  expect(body.evidence.some((e: { document_version_id: string }) => e.document_version_id === candidate.document_version_id)).toBeTruthy();
});
