import { expect, test } from '@playwright/test';
test('monitor pause and resume persist with audited versions after reload', async ({ page, request }) => {
  const listing = await request.get('/api/v1/event-research');
  const item = (await listing.json()).items.find((entry: { event_title: string }) => entry.event_title === '监控计划浏览器验收');
  expect(item).toBeTruthy();
  const path = `/api/v1/research-cases/${item.case_id}/monitor`;
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByRole('button', { name: '查看监控计划', exact: true }).click();
  await expect(page.getByText('调度中', { exact: true })).toBeVisible();
  await page.getByLabel('操作人', { exact: true }).fill('监控验收研究员');
  await page.getByLabel('监控变更原因').fill('等待新材料');
  await page.getByRole('button', { name: '暂停未来调度' }).click();
  await expect(page.getByText('已暂停', { exact: true })).toBeVisible();
  const paused = await (await request.get(path)).json();
  expect(paused.monitor.status).toBe('paused');
  expect(paused.next_scheduled_at).toBeNull();
  expect(paused.monitor.change_reason).toBe('等待新材料');
  await page.reload();
  await page.getByRole('button', { name: '查看监控计划', exact: true }).click();
  await expect(page.getByText('已暂停', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('操作人', { exact: true }).fill('监控验收研究员');
  await page.getByLabel('监控变更原因').fill('恢复跟踪');
  await page.getByRole('button', { name: '恢复未来调度' }).click();
  await expect(page.getByText('调度中', { exact: true })).toBeVisible();
  const resumed = await (await request.get(path)).json();
  expect(resumed.monitor.version).toBe(paused.monitor.version + 1);
  expect(resumed.monitor.changed_by).toBe('监控验收研究员');
  expect(resumed.next_scheduled_at).toBeTruthy();
  expect(resumed.history).toHaveLength(3);
  await page.getByRole('button', { name: '配置监控计划', exact: true }).click();
  await page.getByLabel('单次任务额度').fill('30');
  await page.getByLabel('监控频率', { exact: true }).selectOption('weekday_08_30');
  await page.getByLabel('配置变更原因', { exact: true }).fill('改为晨间验证');
  await page.getByLabel('我已核对范围与预算，同意启用未来调度').check();
  await page.getByRole('button', { name: '保存并启用监控' }).click();
  await expect(page.getByText('监控配置已保存，当前版本 4。')).toBeVisible();
  const configured = await (await request.get(path)).json();
  expect(configured.monitor.budget).toBe(30);
  expect(configured.monitor.frequency).toBe('weekday_08_30');
  expect(configured.monitor.change_reason).toBe('改为晨间验证');
  await page.reload();
  await page.getByRole('button', { name: '配置监控计划', exact: true }).click();
  await expect(page.getByLabel('单次任务额度')).toHaveValue('30');
  await expect(page.getByLabel('监控频率', { exact: true })).toHaveValue('weekday_08_30');
  const concurrentPause = await request.post(`${path}/paused`, { data: { actor: '另一位研究员', change_reason: '暂停检查新材料' } });
  expect(concurrentPause.ok()).toBeTruthy();
  await page.getByLabel('操作人', { exact: true }).fill('监控验收研究员');
  await page.getByLabel('配置变更原因', { exact: true }).fill('旧页面尝试保存');
  await page.getByLabel('我已核对范围与预算，同意启用未来调度').check();
  await page.getByRole('button', { name: '保存并启用监控' }).click();
  await expect(page.getByRole('alert')).toContainText('状态已变化');
  await expect(page.getByRole('button', { name: '保存并启用监控' })).toBeDisabled();
  const afterConflict = await (await request.get(path)).json();
  expect(afterConflict.monitor.version).toBe(5);
  expect(afterConflict.monitor.status).toBe('paused');


  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test('first monitor creation requires explicit scope and persists version one', async ({ page, request }) => {
  const listing = await request.get('/api/v1/event-research');
  const item = (await listing.json()).items.find((entry: { event_title: string }) => entry.event_title === '监控新建浏览器验收');
  expect(item).toBeTruthy();
  const path = `/api/v1/research-cases/${item.case_id}/monitor`;
  expect((await (await request.get(path)).json()).monitor).toBeNull();
  await page.goto(`/?caseId=${item.case_id}`);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('操作人', { exact: true }).fill('首次监控验收');
  await page.getByRole('button', { name: '配置监控计划', exact: true }).click();
  const save = page.getByRole('button', { name: '保存并启用监控' });
  await expect(save).toBeDisabled();
  await page.getByLabel('现金流转化', { exact: true }).check();
  await page.getByLabel('公司披露', { exact: true }).check();
  await page.getByLabel('下一核验事件', { exact: true }).fill('下一季度现金流披露');
  await page.getByLabel('配置变更原因', { exact: true }).fill('建立首个核验计划');
  await expect(save).toBeDisabled();
  const consent = page.getByLabel('我已核对范围与预算，同意启用未来调度');
  await consent.check();
  await page.getByLabel('单次任务额度').fill('12');
  await expect(consent).not.toBeChecked();
  await expect(save).toBeDisabled();
  await consent.check();
  const write = page.waitForResponse((response) => response.url().endsWith(path) && response.request().method() === 'PUT');
  await save.click();
  const saved = await write;
  expect(saved.status()).toBe(200);
  expect(saved.request().postDataJSON().expected_version).toBe(0);
  await expect(page.getByText('监控配置已保存，当前版本 1。')).toBeVisible();
  const current = await (await request.get(path)).json();
  expect(current.monitor.version).toBe(1);
  expect(current.monitor.status).toBe('active');
  expect(current.monitor.budget).toBe(12);
  expect(current.monitor.allowed_source_types).toEqual(['company_disclosure']);
  expect(current.monitor.factor_ids).toHaveLength(1);
  expect(current.history).toHaveLength(1);
  await page.reload();
  await page.getByRole('button', { name: '查看监控计划', exact: true }).click();
  await expect(page.getByText('调度中', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '核对监控范围与协议', exact: true }).click();
  await expect(page.getByText('无需研究协议', { exact: true })).toBeVisible();
  await expect(page.getByText('继续既有研究流程', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '配置监控计划', exact: true }).click();
  await expect(page.getByLabel('单次任务额度')).toHaveValue('12');
  await expect(page.getByLabel('现金流转化', { exact: true })).toBeChecked();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByLabel('监控频率', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/monitor-create-mobile.png' });
  await page.getByLabel('操作人', { exact: true }).fill('单次启动验收');
  await page.getByLabel('单次研究启动原因').fill('核对冻结计划后启动');
  await page.getByLabel('我已核对上述范围和额度，确认启动一次研究').check();
  const returnedIds: string[] = [];
  await page.route('**/monitor/runs', async (route) => {
    const response = await route.fetch();
    expect(response.status()).toBe(201);
    returnedIds.push((await response.json()).id);
    if (returnedIds.length === 1) await route.abort('failed');
    else await route.fulfill({ response });
  });
  await page.getByRole('button', { name: '按此计划启动一次研究' }).click();
  await expect(page.getByRole('alert')).toContainText('无法连接');
  await page.reload();
  await page.getByLabel('操作人', { exact: true }).fill('单次启动验收');
  await page.getByRole('button', { name: '核对监控范围与协议', exact: true }).click();
  await page.getByLabel('单次研究启动原因').fill('核对冻结计划后启动');
  await page.getByLabel('我已核对上述范围和额度，确认启动一次研究').check();
  await page.getByRole('button', { name: '按此计划启动一次研究' }).click();
  await expect(page.getByText(/研究已排队，运行编号：/)).toBeVisible();
  expect(returnedIds).toHaveLength(2);
  expect(returnedIds[0]).toBe(returnedIds[1]);
  const runs = await (await request.get(`/api/v1/research-cases/${item.case_id}/runs`)).json();
  expect(runs.items).toHaveLength(1);
  const events = await (await request.get(`/api/v1/research-runs/${returnedIds[0]}/events`)).json();
  expect(events.items.some((event: { details: { requested_by?: string } }) => event.details.requested_by === '单次启动验收')).toBeTruthy();

});

test('blocked protocol prevents manual start in both UI and API', async ({ page, request }) => {
  const listing = await request.get('/api/v1/event-research');
  const item = (await listing.json()).items.find((entry: { event_title: string }) => entry.event_title === '协议阻断浏览器验收');
  expect(item).toBeTruthy();
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByLabel('操作人', { exact: true }).fill('协议门禁验收');
  await page.getByRole('button', { name: '核对监控范围与协议', exact: true }).click();
  await expect(page.getByText('协议尚未通过', { exact: true })).toBeVisible();
  await expect(page.getByText('确认结果指标、范围、基线和时间窗', { exact: true })).toBeVisible();
  await page.getByLabel('单次研究启动原因').fill('核验阻断状态');
  await page.getByLabel('我已核对上述范围和额度，确认启动一次研究').check();
  await expect(page.getByRole('button', { name: '按此计划启动一次研究' })).toBeDisabled();
  const blocked = await request.post(`/api/v1/research-cases/${item.case_id}/monitor/runs`, { data: {
    actor: '协议门禁验收', change_reason: '服务端协议检查', expected_version: 1, idempotency_key: 'browser-protocol-blocked',
  } });
  expect(blocked.status()).toBe(422);
  const runs = await (await request.get(`/api/v1/research-cases/${item.case_id}/runs`)).json();
  expect(runs.items).toHaveLength(0);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
