import { expect, test } from "@playwright/test";

test("run history paginates and a human cancellation persists after reload", async ({ page, request }) => {
  const listing = await request.get("/api/v1/event-research");
  expect(listing.ok()).toBeTruthy();
  const item = (await listing.json()).items.find((entry: { event_title: string }) => entry.event_title === "运行操作浏览器验收");
  expect(item).toBeTruthy();
  const runs = await request.get(`/api/v1/research-cases/${item.case_id}/runs`);
  const run = (await runs.json()).items[0];
  expect(run.status).toBe("queued");
  await page.goto(`/?caseId=${item.case_id}`);
  await page.getByLabel("操作人", { exact: true }).fill("运行验收研究员");
  await page.getByRole("button", { name: "查看研究累计模型用量", exact: true }).click();
  await expect(page.getByRole("region", { name: "研究累计模型用量", exact: true })).toContainText("暂无可归属的调用记录，不能据此认定用量为零。");
  await page.getByRole("button", { name: "查看运行详情", exact: true }).click();
  await expect(page.getByText("隔离运行历史 1", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "查看模型用量", exact: true }).click();
  await expect(page.getByRole("region", { name: "模型用量", exact: true })).toContainText("暂无可归属的调用记录，不能据此认定用量为零。");
  await page.getByRole("button", { name: "加载更多事件", exact: true }).click();
  await expect(page.getByText("隔离运行历史 55", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByLabel("取消原因", { exact: true }).fill("已核验运行记录，停止本次隔离验收运行。");
  const cancellation = page.waitForResponse((r) => r.url().endsWith(`/research-runs/${run.id}/cancel`) && r.request().method() === "POST");
  await page.getByRole("button", { name: "确认取消本次运行", exact: true }).click();
  expect((await cancellation).status()).toBe(200);
  const persisted = await request.get(`/api/v1/research-runs/${run.id}`);
  expect((await persisted.json()).status).toBe("cancelled");
  await page.reload();
  await page.getByRole("button", { name: "查看运行详情", exact: true }).click();
  await expect(page.getByRole("button", { name: "确认取消本次运行", exact: true })).toBeDisabled();
  const history = await request.get(`/api/v1/research-runs/${run.id}/events?limit=200`);
  expect((await history.json()).items.some((event: { details: { actor?: string; change_reason?: string } }) => event.details.actor === "运行验收研究员" && event.details.change_reason === "已核验运行记录，停止本次隔离验收运行。")).toBeTruthy();
  await page.getByRole("button", { name: "确认取消本次运行", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/run-controls.png" });
});
